### ISSUE TITLE
mlogvis: Allow empty namespaces to be hidden/toggled from the legend (like Lockpingers)

### ISSUE THREAD

**Issue by gianpaj** [rueckstiess/mtools#119]
When there are log lines without a namespace like lockpingers you can't click on them to hide/toggle them.

See here:
https://www.evernote.com/shard/s1/sh/097291cb-c0fe-40e4-9161-f8de8e8e473e/9517131d79e00366fafe49b840a1582d

**Comment by stennie** [comment]
Closing as #wontfix per #776
