### ISSUE TITLE
mlaunch: Support --ssl option to automatically setup a fully SSL-enabled cluster

### ISSUE THREAD

**Issue by devkev** [rueckstiess/mtools#127]
Assuming you already have an SSL-enabled build.  Currently you have to muck about generating a keypair with openssl, followed by adding `--sslOnNormalPorts` and `--sslPEMKeyFile <filename>` to the command line.

**Comment by stennie** [comment]
Fixed with PR#524

**Comment by p-mongo** [comment]
#524 adds a bunch of SSL options but it does not appear that it has any functionality to generate the apparently required pem file to launch an SSL-enabled cluster.
