### ISSUE TITLE
mplotqueries: make it backwards compatible with matplotlib < 1.2.1

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#132]
In particular, the fontsize keyword for legend() was only introduced in 1.2.1.

Mavericks seems to ship with an outdated version of matplotlib 1.1.1. Handling this one case should make it backwards compatible.

Also see:
http://stackoverflow.com/questions/7125009/how-to-change-legend-size-with-matplotlib-pyplot

**Comment by stennie** [comment]
Closing as #wontfix .. it's been 2 1/2 years and versions have moved on.

To check your version of matplotlib:
```
python -c 'import matplotlib; print matplotlib.__version__'
```

For information on installing a newer version of matplotlib on OS X (if required), see: https://github.com/rueckstiess/mtools/wiki/matplotlib-Installation-Guide-for-Mac-OS-X
