### ISSUE TITLE
logline parses balancer query failures wrongly as queries

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#142]
```
Wed Nov 20 13:13:37.794 [Balancer] query failed to: <hostname>:9002 exception: socket exception [FAILED_STATE] for <hostname>:9002
```

This is interpreted as a query with a "failed" namespace. Should be caught as an exception to the rule. For example, check namespace for . in the middle. or explicitly catch `query failed`.

**Comment by stennie** [comment]
Closing old issues to clean up the backlog. If this is still an issue with modern (non-EOL) versions of MongoDB, please open a new issue with an example log line.
