### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by derickr** [rueckstiess/mtools#147]
Hey Thomas,

It'd be awesome if there was a Debian package. Then I wouldn't have to install out-of-apt packages that can clutter my machine.

cheers,
Derick

**Comment by stennie** [comment]
We don't have any volunteers with bandwidth to maintain O/S package so closing this to clear up the backlog.

I made a Docker image a while ago which might be of interest: https://hub.docker.com/r/stennie/ubuntu-mtools/

Regards,
Stennie
