### ISSUE TITLE
mlaunch: support ~/.mlaunchrc or similar

### ISSUE THREAD

**Issue by devkev** [rueckstiess/mtools#188]
Since I run on Linux, I usually need to specify `--smallfiles --oplogSize 100` to avoid using a lot of disk space.  It would be great if I could put these defaults into an rc file of some sort, eg. `$HOME/.mlaunchrc`.  Not sure the best way to make these settings easily overridable.  Perhaps a `--norc` option to ignore the rc file?

**Comment by stennie** [comment]
The easiest solution for this would be to add an `alias` with your favourite command-line values.

Given the age of this feature suggestion, I don't think it will be implemented in the near future so am closing to clean up the backlog :)
