### ISSUE TITLE
mlaunch sharded cluster returns before initialization is complete?

### ISSUE THREAD

**Issue by mhelmstetter** [rueckstiess/mtools#195]
It seems like mlaunch when run in non-verbose mode returns before the cluster initialization is complete? But it seems as if it does not return until initialization is complete when running with --verbose. It seems like the command should not return until initialization is complete.

Here's what I've got. After running mlaunch I connect via mongo shell and sharding has not yet been initialized.

# mlaunch --single --sharded 3 --dir /data
launching: mongod on port 27018
launching: mongod on port 27019
launching: mongod on port 27020
launching: config server on port 27021
launching: mongos on port 27017
[root@ip-10-151-123-15 shard01]# mongo
MongoDB shell version: 2.4.9
connecting to: test
mongos> sh.status()
--- Sharding Status --- 
  sharding version: {
        "_id" : 1,
        "version" : 3,
        "minCompatibleVersion" : 3,
        "currentVersion" : 4,
        "clusterId" : ObjectId("5307706b459f45bd0ef3c8ca")
}
  shards:
  databases:
        {  "_id" : "admin",  "partitioned" : false,  "primary" : "config" }

mongos>

**Comment by rueckstiess** [comment]
seems to have been fixed a while ago.
