### ISSUE TITLE
Compile errors with XCode 5.1 (clang 3.4)

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#203]
It appears some people get install errors when installing/upgrading to mtools 1.1.4 on Mac OS X Mavericks:

```
clang: error: unknown argument: '-mno-fused-madd' [-Wunused-command-line-argument-hard-error-in-future]
```

This is due to the latest XCode 5.1 update, that seems to fundamentally break C-extensions for native Apple Python installations. mtools itself doesn't use C-extensions, but depends on psutil, which does. 

There is a work-around, see: 
http://stackoverflow.com/questions/22313407/clang-error-unknown-argument-mno-fused-madd-python-package-installation-fa
And also: 
http://alyssafrazee.com/dangit-mavericks.html  (guess where Alyssa found the solution?)

You need to run the pip command with a prefix to define some compiler flags:

```
ARCHFLAGS=-Wno-error=unused-command-line-argument-hard-error-in-future pip install mtools
```

To get a clean install you may want to `pip uninstall mtools psutil` before.

Feel free to comment on this issue if you still have any problems installing.

**Comment by stennie** [comment]
There don't appear to be any newer reports of this problem and versions have moved on in the past few years (OS X 10.11 / El Capitan, Clang 7.3.x) .. so closing once again :).

Thanks,
Stennie
