### ISSUE TITLE
restructure mloginfo argument interface 

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#224]
I've added the new mloginfo command interface. It's currently in the [mloginfo-commands](https://github.com/rueckstiess/mtools/tree/mloginfo-commands) branch. 

The new usage of mloginfo would be:

```
mloginfo <command> <logfile> [additional optional arguments]
```

For example `mloginfo queries mongod.log --sort min`.

Adding sub-sections is quite simple. If you want no extra arguments, just look at the [restarts section](https://github.com/rueckstiess/mtools/blob/mloginfo-commands/mtools/mloginfo/sections/restart_section.py). All you have to provide is a `name` and a `description` class variable, the rest is done automatically (i.e. command added to the parser, correct section invoked). And you need to import the section in `sections/__init__.py`.

If you want to add extra arguments, have a look at the [queries section](https://github.com/rueckstiess/mtools/blob/mloginfo-commands/mtools/mloginfo/sections/query_section.py#L20-22). You add a method `_add_subparser_arguments(self, subparser)` and add them on the subparser object. 

You can then access them within a section with `self.mloginfo.args['foo']` (for argument `foo`).

**Comment by stennie** [comment]
Closing old issues to clean up the backlog. `mloginfo` has continued to use the previous interface and this branch is now 6 years and 500+ commits behind.
