### ISSUE TITLE
Script installation process doesn't work cross platform

### ISSUE THREAD

**Issue by turtlemonvh** [rueckstiess/mtools#229]
Esp. on Windows the installation works, but the way the scripts are set up they are not placed on the user's path.  Setuptools has [a way to fix this](https://pythonhosted.org/setuptools/setuptools.html#automatic-script-creation).  I have a pull request I'm submitting that solves this.

**Comment by stennie** [comment]
Looks like this was addressed and merged with #230.

Regards,
Stennie
