### ISSUE TITLE
Fix documentation mentioning "development mode"

### ISSUE THREAD

**Issue by turtlemonvh** [rueckstiess/mtools#231]
All three of these documentation sections mention that `python setup.py develop` is the best way to setup the environment for working on scripts.
- https://github.com/rueckstiess/mtools/blob/master/tutorials/contributing.md#development-installation
- https://github.com/rueckstiess/mtools/blob/master/INSTALL.md#installation-from-source
- https://github.com/rueckstiess/mtools/wiki/mtools-Development-Mode

However, pip has [the "Editable Installs" option](http://pip.readthedocs.org/en/latest/reference/pip_install.html#editable-installs) that does the same thing.

So instead of

```
cd /path/to/cloned/repo
python setup.py develop
```

You can

```
pip install -e /path/to/cloned/repo
```

I think this approach is a bit more consistent and easy to work with.

**Comment by stennie** [comment]
@turtlemonvh FYI, this has been updated in the latest `develop` branch (which will be mtools 1.2.4): https://github.com/rueckstiess/mtools/blob/develop/INSTALL.md#installation-from-source.
