### ISSUE TITLE
mgenerate: Implement $timestamp operator

### ISSUE THREAD

**Issue by gianpaj** [rueckstiess/mtools#246]

**Comment by chrisdamba** [comment]
Hi, would be interested in this if I could get a bit of more context. Is it similar to the mongoose [`timestamps`](http://mongoosejs.com/docs/guide.html#timestamps) which assigns `createdAt` and `updatedAt` fields to your schema?

**Comment by rueckstiess** [comment]
Hi @chrisdamba,

Thanks for the interest. But unfortunately, mtools' mgenerate is now deprecated and we won't add any more features to it. Please use the new standalone implementation [mgeneratejs](https://github.com/rueckstiess/mgeneratejs).

It's faster and has more features (including timestamping).

**Comment by chrisdamba** [comment]
Thanks @rueckstiess for the update!

**Comment by rueckstiess** [comment]
No problem @chrisdamba! You are more than welcome to contribute to mgeneratejs and/or other parts of mtools though!
