### ISSUE TITLE
create Windows installer for mtools

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#254]
@stennie may be looking into this if time allows.

**Comment by stennie** [comment]
Investigation into various install options didn't result in any easy wins; closing this to clean up the backlog.

Windows 10 has the option of [Ubuntu on Windows](https://www.microsoft.com/en-us/p/ubuntu/9nblggh4msv6?activetab=pivot%3Aoverviewtab), which simplifies challenges around build toolchain and dependencies for Windows installation.
