### ISSUE TITLE
Allow --replicaset to accept a number (replacing --nodes parameter)

### ISSUE THREAD

**Issue by victorhooi** [rueckstiess/mtools#276]
Hi,

I'm trying to create a 3-node replicaset with a primary, secondary and arbiter. For some reason, no matter what options I use, `mlaunch` seems to create a replica-set with four nodes. For example, the wiki page (https://github.com/rueckstiess/mtools/wiki/mlaunch) mentions that the argument to `--replicaset` specifies the number of data-bearing nodes - so I thought the following would work:
```
> mlaunch init --replicaset 2 --arbiter --auth
launching: mongod on port 27017
launching: mongod on port 27018
launching: mongod on port 27019
launching: mongod on port 27020
replica set 'replset' initialized.
waiting for primary to add a user.
> mlaunch list

PROCESS    STATUS     PORT

primary    running    27017
mongod     running    27018
mongod     running    27019
arbiter    running    27020
```
However, this seems to result in one primary, two secondaries, and an arbiter.

I then tried with `--replicaset 1`:
```
> mlaunch init --replicaset 1 --arbiter --auth
launching: mongod on port 27017
launching: mongod on port 27018
launching: mongod on port 27019
launching: mongod on port 27020
replica set 'replset' initialized.
waiting for primary to add a user.
> mlaunch list

PROCESS      STATUS     PORT

primary      running    27017
secondary    running    27018
secondary    running    27019
arbiter      running    27020
```

I am using 1.1.5. Any thoughts?

**Comment by rueckstiess** [comment]
Prefer not to introduce any interface changes now. Closing.
