### ISSUE TITLE
command-line parameter for logfile not parsed when run via cron/logrotate

### ISSUE THREAD

**Issue by eadasiak** [rueckstiess/mtools#304]
I'm trying to run both mlogfilter and mloginfo via a script run when the Mongo logs are rotated via logrotate.  This is on a CentOS 6 machine running python 2.6.6 and mtools 1.1.6.  At its most basic, the commands take the following form:

<pre><code>
/usr/bin/mloginfo [logfile] --no-progressbar --verbose --queries --restarts --connections --rsstate >> /tmp/mongo-report.txt 2>&1
/usr/bin/mlogfilter [logfile] --human --scan >> /tmp/mongo-report.txt 2>&1
</code></pre>

These both work fine when run from the command line, but when run via logrotate, it doesn't appear to parse the log file name correctly.  Since that wasn't working, I tried just running the script via cron with hard-coded log file names:

<pre><code>
0 6 * * * /usr/bin/mloginfo /raid/log/mongo.log.1 --no-progressbar --verbose --queries --restarts --connections --rsstate >> /tmp/mongo-report.txt 2>&1
</code></pre>

results in "this tool can't parse input from stdin." 

<pre><code>
5 6 * * * /usr/bin/mlogfilter /raid/log/mongo.log.1 --human --scan >> /tmp/mongo-report.txt 2>&1 
results in this error:
"usage: mlogfilter [-h] [--version] [--no-progressbar] [--verbose]
                  [--shorten [LENGTH]] [--exclude] [--human] [--json]
                  [--markers [MARKERS [MARKERS ...]]] [--timezone [N [N ...]]]
                  [--timestamp-format {none,ctime-pre2.4,ctime,iso8601-utc,iso8601-local}]
                  [--from [FROM [FROM ...]]] [--to [TO [TO ...]]]
                  [--fast [FAST]] [--namespace NS] [--operation OP]
                  [--thread THREAD] [--pattern PATTERN] [--mask MASK]
                  [--mask-size MASK_SIZE] [--mask-center {start,end,both}]
                  [--slow [SLOW]] [--scan] [--word [WORD [WORD ...]]]
mlogfilter: error: unrecognized arguments: /raid/log/mongo.log.1"
</code></pre>

If there's any trick for getting these scripts to work via either cron or logrotate, I'd appreciate the guidance.

These tools are fantastic and provide a lot of great insight, but not being able to send them out via an automated report really limits their utility.

**Comment by daihu** [comment]
@eadasiak i meet same problem,i how to do
