### ISSUE TITLE
[MLogInfo] [Feature] Parse lines from  clientcursormon, the Thread for timing out old cursors.

### ISSUE THREAD

**Issue by AnneTheAgile** [rueckstiess/mtools#315]
A question and an item possibly I can help fix regarding clientcursormon [1]. 
[] It seems like the string " [clientcursormon]  connections:INTEGER" could be added to the parser to catch the self-tests of connections. Already there are instances of clientcursormon in one of the test files [2], but none with 'connections'. 

[] Is this project related to the MongoDB log parser project, mongodb-log? Its readme says it "Turn[s] mongod log entries to nice objects that are easy to work with." It creates JSON for each log line and lists all of its parser assumptions. It definitely seems like a good helper for parsing MongoDB logs ; 
https://github.com/imlucas/mongodb-log

thank you for this great tool!
AnneTheAgile
Example showing  unmatched lines;
````
$ mloginfo q2.configServers.bugShown.log  --distinct --verbose
     source: q2.configServers.bugShown.log
       host: unknown
      start: 2014 Nov 21 21:47:12.142
        end: 2014 Nov 21 22:16:33.067
date format: iso8601-local
     length: 355
     binary: unknown
    version: >= 2.6 (iso8601 format)

DISTINCT
couldn't match:  m31100| 2014-11-21T21:48:00.064-0500 [clientcursormon]  connections:7
couldn't match:  m29002| 2014-11-21T21:48:08.065-0500 [clientcursormon]  connections:15
couldn't match:  m29001| 2014-11-21T21:48:08.069-0500 [clientcursormon]  connections:15
couldn't match:  m29000| 2014-11-21T21:48:11.008-0500 [clientcursormon]  connections:14
couldn't match:  m31100| 2014-11-21T21:53:58.024-0500 [clientcursormon]  connections:7
couldn't match:  m29002| 2014-11-21T21:54:06.026-0500 [clientcursormon]  connections:15
couldn't match:  m29001| 2014-11-21T21:54:06.034-0500 [clientcursormon]  connections:15
couldn't match:  m29000| 2014-11-21T21:54:08.969-0500 [clientcursormon]  connections:14
couldn't match:  m31100| 2014-11-21T21:58:58.095-0500 [clientcursormon]  connections:7
couldn't match:  m29002| 2014-11-21T21:59:06.098-0500 [clientcursormon]  connections:15
couldn't match:  m29001| 2014-11-21T21:59:06.110-0500 [clientcursormon]  connections:15
couldn't match:  m29000| 2014-11-21T21:59:09.043-0500 [clientcursormon]  connections:14
couldn't match:  m31100| 2014-11-21T22:03:58.163-0500 [clientcursormon]  connections:7
couldn't match:  m29002| 2014-11-21T22:04:06.171-0500 [clientcursormon]  connections:15
couldn't match:  m29001| 2014-11-21T22:04:06.184-0500 [clientcursormon]  connections:15
couldn't match:  m29000| 2014-11-21T22:04:09.114-0500 [clientcursormon]  connections:14
couldn't match:  m31100| 2014-11-21T22:08:58.242-0500 [clientcursormon]  connections:7
couldn't match:  m29002| 2014-11-21T22:09:06.248-0500 [clientcursormon]  connections:15
couldn't match:  m29001| 2014-11-21T22:09:06.260-0500 [clientcursormon]  connections:15
couldn't match:  m29000| 2014-11-21T22:09:09.193-0500 [clientcursormon]  connections:14
couldn't match:  m31100| 2014-11-21T22:13:58.310-0500 [clientcursormon]  connections:7
couldn't match:  m29002| 2014-11-21T22:14:06.322-0500 [clientcursormon]  connections:15
couldn't match:  m29001| 2014-11-21T22:14:06.336-0500 [clientcursormon]  connections:15
couldn't match:  m29000| 2014-11-21T22:14:09.271-0500 [clientcursormon]  connections:14

     118    cluster ... pinged successfully at ... by distributed lock pinger ' ... ', sleeping for ... ms
      30    could not verify that config servers are in sync
      24    mem (MB) res: ... virt:
      24    mapped (incl journal view):
       6    replication threads:
       1    deleting queue from: ... of size: ... after ... inactivity ... (normal if any mongos has restarted)
       1    clock skew detected  prev: ... now:

distinct couldn't match 24 lines

//Look for Details; 
$ cat q2.configServers.bugShown.log | grep   "connections"  | wc
      24      96    1722
$ cat q2.configServers.bugShown.log | grep   "connections"
 m31100| 2014-11-21T21:48:00.064-0500 [clientcursormon]  connections:7
 m29002| 2014-11-21T21:48:08.065-0500 [clientcursormon]  connections:15
 m29001| 2014-11-21T21:48:08.069-0500 [clientcursormon]  connections:15
//etc
````
REFS
[1] Definition of clientcursormon as Thread for timing out old cursors found here; 
https://github.com/mongodb/mongo/blob/6a54dd5708f5996bd66c00b48386c95ca95f249f/src/mongo/db/clientcursor.cpp#L260
[2] Searches on this project for clientcursormon show a test log file and usage in the tests.
https://github.com/rueckstiess/mtools/search?utf8=%E2%9C%93&q=clientcursormon&type=Code
https://github.com/rueckstiess/mtools/search?utf8=%E2%9C%93&q=mongod_26.log

**Comment by rueckstiess** [comment]
Hi @AnneTheAgile,

sorry for the delay of this reply. 

For your first question about the distinct output: The `mloginfo --distinct` code parses the entire mongo codebase for occurrences of `log()` or `LOG()` or some other functions/macros that output log lines. It then goes through these lines and collects strings, which it will use to identify a given log line. Unfortunately, the process is quite complex, because the code that outputs log lines can have variables in them. It looks like there is no matching line in the code that has the literal `"connections:"` string.

```
$ git grep "connections:"
src/mongo/util/net/message_server_port.cpp:79:                log() << "connection refused because too many open connections: " << Listener::globalTicketHolder.used() << endl;
```

Therefore `--distinct` can't match the line. Adding these manually would be too time-consuming.

As for [mongodb-log](https://github.com/imlucas/mongodb-log), this project was started by one of my colleagues and an intern. I've been contributing to it as well, with the goal of having a similar log parsing library in Javascript. It doesn't have the full functionality of mtools' log parser yet, but it's getting close and is definitely already usable. 

Hope this answers your questions.

Thomas
