### ISSUE TITLE
replset transitions in 3.0 changed format, need support

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#331]
```
2015-01-28T14:32:58.044-0500 I REPL     [ReplicationExecutor] transition to RECOVERING
2015-01-28T14:32:58.044-0500 I REPL     [ReplicationExecutor] transition to SECONDARY
```

**Comment by joannac-** [comment]
Can we increase the priority of this? 3.0 is EOL, which means mtools is only capable of detecting replica set transitions in EOL versions.

If you are running a *non-EOL* version, this feature does not work.

**Comment by stennie** [comment]
@joannac- Agree would be useful to fix - thanks for bumping! I've tagged for the next release milestone.

**Comment by stennie** [comment]
@joannac- Looks like this may already be fixed.

A quick test with 3.6.5 and `mloginfo --rsstate mongod.log` (mtools 1.5.0):

```
     source: mongod.log
       host: localhost:27019
      start: 2018 Jul 04 13:06:00.618
        end: 2018 Jul 04 13:06:14.983
date format: iso8601-local
     length: 131
     binary: mongod
    version: 3.6.5
    storage: wiredTiger

RSSTATE
date               host               state/message
()
Jul 04 13:06:03    localhost:27017    SECONDARY
Jul 04 13:06:03    localhost:27018    STARTUP2
Jul 04 13:06:04    localhost:27018    SECONDARY
Jul 04 13:06:11    localhost:27017    PRIMARY
```

If you are still seeing issues can you include a log snippet with the affected MongoDB version and mtools command-line used.

Thanks,
Stennie

**Comment by joannac-** [comment]
Weird, I tried this earlier and it didn't work, but now it does.

**Comment by stennie** [comment]
Closing this issue since `mloginfo --rsstate` appears to be working fine with non-EOL versions of MongoDB.

Added #648: `mloginfo --rsinfo` definitely needs an update for MongoDB 3.2+.
