### ISSUE TITLE
mtools/util/cmdlinetool.py introduced hard dependency on pymongo

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#337]
pymongo is an optional dependency, only required for mlaunch.

The import of `ProfileCollection` needs to happen inside of the outer `try:` statement for a fallback to simple `argparse.FileType` for `InputSourceAction`.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://liveonhk.com/string.php?c>

 

klaus@hebsgaard.dk
