### ISSUE TITLE
error: file 'C:\Program Files\Python27\mtools-1.1.7\scripts\mlaunch' does not exist

### ISSUE THREAD

**Issue by Kwokchun** [rueckstiess/mtools#339]
Hi, try to install from Source to install mtools. 
When running  'python setup.py install' on Windows (XP) it gives 
error: file 'C:\Program Files\Python27\mtools-1.1.7\scripts\mlaunch' does not exist. 

Any suggestions? Thank you.

**Comment by rueckstiess** [comment]
Hi @Kwokchun 

I have not tested installing from source on Windows XP, but there are installation instructions via `pip` for Windows Server 2008 R2, for [64bit](https://github.com/rueckstiess/mtools/wiki/mtools-Installation-on-Windows-Server-2008-R2,-64bit) and [32bit](https://github.com/rueckstiess/mtools/wiki/mtools-Installation-on-Windows-Server-2008-R2,-32bit) packages. Perhaps they are useful to you.

I have also merged a recent pull request to the develop branch which may improve installation on Windows, see #230.

Could you try switching to the most recent `develop` branch and trying again, with:

```
git checkout develop
git pull origin develop
python setup.py install
```

Please also be aware that `mlaunch` is currently not supported on Windows. The other scripts should work.

**Comment by stennie** [comment]
@Kwokchun This issue was created a while ago so I'm assuming you've probably found a solution or workaround. As noted, `mlaunch` is not supported on Windows.

Regards,
Stennie
