### ISSUE TITLE
 mplotqueries is not working (but mloginfo and mlogvis work). Attached is the error message from the execution

### ISSUE THREAD

**Issue by martinyuk** [rueckstiess/mtools#340]
mplotqueries  /var/log/mongodb/mongod.log

Traceback (most recent call last):
  File "/usr/bin/mplotqueries", line 5, in <module>
    pkg_resources.run_script('mtools==1.1.6', 'mplotqueries')
  File "/usr/lib/python2.6/site-packages/distribute-0.6.28-py2.6.egg/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/distribute-0.6.28-py2.6.egg/pkg_resources.py", line 1239, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/mtools-1.1.6-py2.6.egg/EGG-INFO/scripts/mplotqueries", line 26, in <module>
    raise ImportError("Can't import matplotlib. See https://github.com/rueckstiess/mtools/blob/master/INSTALL.md for instructions how to install matplotlib or try mlogvis instead, which is a simplified version of mplotqueries that visualizes the logfile in a web browser.")
ImportError: Can't import matplotlib. See https://github.com/rueckstiess/mtools/blob/master/INSTALL.md for instructions how to install matplotlib or try mlogvis instead, which is a simplified version of mplotqueries that visualizes the logfile in a web browser.

**Comment by rueckstiess** [comment]
It appears mplotqueries cannot load "matplotlib" (a python scientific plotting library). Can you please run the following command at your command prompt: 

```
python -c "import matplotlib; print matplotlib.__version__"
```

If matplotlib is installed, this should print out its version, e.g. `1.4.1`. If you get an `ImportError` instead, then matplotlib is not installed and you need to install it on your system in order to use mplotqueries. 

If you let me know what OS you are using I can point you to documentation how to install matplotlib.

**Comment by martinyuk** [comment]
Hi Thomas,

Thanks for taking time to look into my issue.

You asked:

python -c "import matplotlib; print matplotlib.__version__"



0.99.1.1


If you let me know what OS you are using I can point you to documentation how to install matplotlib.

This is redhat linux

Linux sflpetemongod002 2.6.32-358.el6.x86_64 #1 SMP Tue Jan 29 11:47:41 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

When I installed matplotlib, I received the following:

python setup.py install
============================================================================
Edit setup.cfg to change the build options

BUILDING MATPLOTLIB
            matplotlib: yes [1.3.1]
                python: yes [2.6.6 (r266:84292, Oct 12 2012, 14:23:48)  [GCC
                        4.4.6 20120305 (Red Hat 4.4.6-4)]]
              platform: yes [linux2]

REQUIRED DEPENDENCIES AND EXTENSIONS
                 numpy: yes [version 1.8.0]
             dateutil: yes [using dateutil version 2.2]
               tornado: yes [using tornado version 2.2.1]
             pyparsing: yes [pyparsing was not found. It is required for
                        mathtext support. pip/easy_install may attempt to
                        install it after matplotlib.]
                 pycxx: yes [Couldn't import.  Using local copy.]
                libagg: yes [pkg-config information for 'libagg' could not
                        be found. Using local copy.]
              freetype: no  [pkg-config information for 'freetype2' could
                        not be found.]
                   png: yes [pkg-config information for 'libpng' could not
                        be found. Using unknown version.]

OPTIONAL SUBPACKAGES
           sample_data: yes [installing]
              toolkits: yes [installing]
                 tests: yes [using nose version 1.3.0]

OPTIONAL BACKEND EXTENSIONS
                macosx: no  [Mac OS-X only]
                qt4agg: yes [installing, Qt: 4.6.2, PyQt4: 4.6.2]
               gtk3agg: no  [Requires pygobject to be installed.]
             gtk3cairo: no  [Requires cairo to be installed.]
                gtkagg: no  [Requires pygtk]
                 tkagg: no  [TKAgg requires Tkinter.]
                 wxagg: no  [requires wxPython]
                   gtk: no  [Requires pygtk]
                   agg: yes [installing]
                 cairo: no  [cairo not found]
             windowing: no  [Microsoft Windows only]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: no
                 latex: no
               pdftops: no

============================================================================
                        * The following required packages can not be built:
                        * freetype
[root@sflpetemongod002 matplotlib-1.3.1]#

Thanks,
Martin

**Comment by martinyuk** [comment]
Hi rueckstiess;

Any chance that you have reviewed my issue? Thx.

Martin


From: Martin Yuk
Sent: Thursday, February 26, 2015 6:38 AM
To: rueckstiess/mtools; rueckstiess/mtools
Subject: RE: [mtools] mplotqueries is not working (but mloginfo and mlogvis work). Attached is the error message from the execution (#340)

Hi Thomas,

Thanks for taking time to look into my issue.

You asked:


python -c "import matplotlib; print matplotlib.__version__"



0.99.1.1


If you let me know what OS you are using I can point you to documentation how to install matplotlib.

This is redhat linux

Linux sflpetemongod002 2.6.32-358.el6.x86_64 #1 SMP Tue Jan 29 11:47:41 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

When I installed matplotlib, I received the following:

python setup.py install
============================================================================
Edit setup.cfg to change the build options

BUILDING MATPLOTLIB
            matplotlib: yes [1.3.1]
                python: yes [2.6.6 (r266:84292, Oct 12 2012, 14:23:48)  [GCC
                        4.4.6 20120305 (Red Hat 4.4.6-4)]]
              platform: yes [linux2]

REQUIRED DEPENDENCIES AND EXTENSIONS
                 numpy: yes [version 1.8.0]
             dateutil: yes [using dateutil version 2.2]
               tornado: yes [using tornado version 2.2.1]
             pyparsing: yes [pyparsing was not found. It is required for
                        mathtext support. pip/easy_install may attempt to
                        install it after matplotlib.]
                 pycxx: yes [Couldn't import.  Using local copy.]
                libagg: yes [pkg-config information for 'libagg' could not
                        be found. Using local copy.]
              freetype: no  [pkg-config information for 'freetype2' could
                        not be found.]
                   png: yes [pkg-config information for 'libpng' could not
                        be found. Using unknown version.]

OPTIONAL SUBPACKAGES
           sample_data: yes [installing]
              toolkits: yes [installing]
                 tests: yes [using nose version 1.3.0]

OPTIONAL BACKEND EXTENSIONS
                macosx: no  [Mac OS-X only]
                qt4agg: yes [installing, Qt: 4.6.2, PyQt4: 4.6.2]
               gtk3agg: no  [Requires pygobject to be installed.]
             gtk3cairo: no  [Requires cairo to be installed.]
                gtkagg: no  [Requires pygtk]
                 tkagg: no  [TKAgg requires Tkinter.]
                 wxagg: no  [requires wxPython]
                   gtk: no  [Requires pygtk]
                   agg: yes [installing]
                 cairo: no  [cairo not found]
             windowing: no  [Microsoft Windows only]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: no
                 latex: no
               pdftops: no

============================================================================
                        * The following required packages can not be built:
                        * freetype
[root@sflpetemongod002 matplotlib-1.3.1]#

Thanks,
Martin

**Comment by rueckstiess** [comment]
Hi @martinyuk,

based on these outputs, it looks like the freetype library is not installed, which is a dependency for matplotlib.

```
freetype: no  [pkg-config information for 'freetype2' could not be found.]
```
```
 * The following required packages can not be built:
                        * freetype
```

I have written up an install guide for some OS (see wiki), but not for Redhat yet. But [this step](https://github.com/rueckstiess/mtools/wiki/mtools-Installation-on-Ubuntu-12.04#5-install-matplotlib) from the Ubuntu guide might still be of interest, particularly the part that installs the dependencies `libpng-dev libjpeg8-dev libfreetype6-dev`. You'll have to install equivalent packages with yum.

**Comment by stennie** [comment]
Hi @martinyuk,

This issue was created a while ago so I'm assuming you've either found a solution or upgraded to a newer environment by now. If you did find a solution, it could help others if you comment here with the outcome.

Regards,
Stennie
