### ISSUE TITLE
mplotqueries not working (get the error about matplotlib,but the matplotlib is already installed )

### ISSUE THREAD

**Issue by eshujiushiwo** [rueckstiess/mtools#345]
The error is 
Traceback (most recent call last):
  File "/usr/bin/mplotqueries", line 9, in <module>
    load_entry_point('mtools==1.1.8', 'console_scripts', 'mplotqueries')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 349, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2543, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2237, in load
  File "/usr/lib/python2.6/site-packages/mtools/mplotqueries/mplotqueries.py", line 26, in <module>
    raise ImportError("Can't import matplotlib. See https://github.com/rueckstiess/mtools/blob/master/INSTALL.md for instructions how to install matplotlib or try mlogvis instead, which is a simplified version of mplotqueries that visualizes the logfile in a web browser.")
ImportError: Can't import matplotlib. See https://github.com/rueckstiess/mtools/blob/master/INSTALL.md for instructions how to install matplotlib or try mlogvis instead, which is a simplified version of mplotqueries that visualizes the logfile in a web browser.

And the result of "python -c "import matplotlib; print matplotlib.__version__" is 1.4.3

**Comment by rueckstiess** [comment]
Can you also run 
```
python --version
```

It's possible that you have multiple python versions installed and only one of them has matplotlib but not the other. mtools seems to be installed under python2.6/site-packages. 

```
File "/usr/lib/python2.6/site-packages/mtools/mplotqueries/mplotqueries.py", line 26, in 
```

if you shell python points to python 2.7 you'll have install mtools with that version again and possibly fix your path or python links.

**Comment by eshujiushiwo** [comment]
HI 
Thanks for the reply.
The result of python --version is
Python 2.6.6
and i found out that the matplotilib is already in the path /usr/lib/python2.6/site-packages/matplotlib

**Comment by rueckstiess** [comment]
Hm this is a bit strange. I'm not exactly sure what is going on. Perhaps a clean re-install of matplotlib and mtools might fix it? 

But before you do that, can you try one more thing? Can you try to import matplotlib with specifically that python version? E.g.

```
/usr/bin/python2.6 -m "import matplotlib; print matplotlib.__version__"
```

I still think there is something strange with the python installation(s) going on, as mtools only tries to import matplotlib and if that throws an ImportError it prints out that message.

**Comment by johnleetran** [comment]
I had the same issue.  I was able to resolve the issue by doing

```sudo pip uninstall python-dateutil```
```sudo pip install python-dateutil==2.2```
