### ISSUE TITLE
Transition mplotqueries to command-style argument parsing

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#348]
plot types can have specific parameters, for example `--yaxis` for scatter plots. 

mplotqueries should adopt the command-style parsing (like e.g. `git`). The commands should represent the different plot styles/types.

```
Usage: 
  mplotqueries <style> [<options>]
  mplotqueries -h | --help

Options:
  ...

Styles: 
  Available styles are scatter, histogram, range, event, rsstate, connchurn, durline.
  Use `mplotqueries <style> --help` for specific options and help on that style.
```

**Comment by stennie** [comment]
Closing old issue to clean up the backlog. This would be a breaking change better saved for a significant rewrite.
