### ISSUE TITLE
mlaunch to support optional storage engines 

### ISSUE THREAD

**Issue by nleite** [rueckstiess/mtools#349]
We should include option for 3.0 different storage engine options like wiredTiger: `--storageEngine wiredTiger` being the default `mmapv1`

**Comment by stennie** [comment]
@nleite `mlaunch` passes through any unknown options to the `mongod` binary so this is already supported.

**Comment by rueckstiess** [comment]
Yep, @stennie is right, this works already:
```
mlaunch init --single --storageEngine wiredTiger
...
mongo --eval "JSON.stringify(db.serverStatus()['storageEngine'])"
MongoDB shell version: 3.0.0
connecting to: test
{"name":"wiredTiger"}
```

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://neswf.jetnic.in/christian.php?aca>

 

klaus@hebsgaard.dk
