### ISSUE TITLE
mlaunch should print error message for invalid options, rather than silently ignoring

### ISSUE THREAD

**Issue by victorhooi** [rueckstiess/mtools#355]
Currently, `mlaunch` will silently ignore any invalid options that you attempt to pass through. For example, the following will not produce any syntax errors:

```
mlaunch init --single --carrots --apples
```

I understand that we will need to check both `mongos` and `mongod` for what is a valid option - however, it would be nice to error out for invalid syntax - otherwise a user may assume something works (e.g. setting storage engine to WiredTiger) when they actually mis-spelt it, and it did not work.

**Comment by monkey101** [comment]
+1
This just snagged me because I was using `--binaryPath` instead of `--binarypath`
