### ISSUE TITLE
"can't start process, return code 100"

### ISSUE THREAD

**Issue by tivivi63** [rueckstiess/mtools#359]
Hello,

Unlike all the other mtools, I am unable to use the "mlaunch init --replicaset --sharded" command. The following command issues an "undocumented" return code 100 error:
$ mlaunch init --replicaset --sharded s1 s2 s3
launching: mongod on port 27018
can't start process, return code 100. tried to launch: mongod --replSet s1 --dbpath /home/m202/data/s1/rs1/db --logpath /home/m202/data/s1/rs1/mongod.log --port 27018 --logappend   --fork

Something I do not understand? Any regression? 
Please advise on what to do.
tivivi63

MongoDB shell version: 2.6.4
mtools version 1.1.5
Ubuntu 14.04 LTS 64-bits

**Comment by rueckstiess** [comment]
Hi @tivivi63 

This error seems to come from mongod directly, not mlaunch. This usually happens when the mongod cannot start for some reason. Is there a log file? Can you check if `/home/m202/data/s1/rs1/mongod.log` exists and paste the last few lines into this ticket? 

If it doesn't exist, then it probably couldn't start one of the processes at all. In that case, double-check if you have write permissions to the directories. It might also help to run mlaunch with additional `--verbose` flag, so you see which process fails to start.

By the way, the same command seems to work for me: 

```
$ mlaunch init --replicaset --sharded s1 s2 s3

launching: mongod on port 27018
launching: mongod on port 27019
launching: mongod on port 27020
launching: mongod on port 27021
launching: mongod on port 27022
launching: mongod on port 27023
launching: mongod on port 27024
launching: mongod on port 27025
launching: mongod on port 27026
launching: config server on port 27027
replica set 's1' initialized.
replica set 's2' initialized.
replica set 's3' initialized.
launching: mongos on port 27017
adding shards. can take up to 30 seconds...

$ mlaunch list

PROCESS          PORT     STATUS     PID

mongos           27017    running    95350

config server    27027    running    95347

s1
    primary      27018    running    95320
    secondary    27019    running    95323
    secondary    27020    running    95326

s2
    primary      27021    running    95329
    secondary    27022    running    95332
    secondary    27023    running    95335

s3
    primary      27024    running    95338
    secondary    27025    running    95341
    secondary    27026    running    95344

```

Hope this helps diagnosing the problem further. Let me know if I can assist more. 

Thomas

**Comment by tivivi63** [comment]
Yes, Thomas, this TRUELY helped. :)

2015-05-04T22:03:41.280+0200 [initandlisten] ERROR: Insufficient free space for journal files
2015-05-04T22:03:41.280+0200 [initandlisten] Please make at least 3379MB available in /home/m202/data/s1/rs1/db/journal or use --smallfiles
2015-05-04T22:03:41.280+0200 [initandlisten] 
2015-05-04T22:03:41.286+0200 [initandlisten] exception in initAndListen: 15926 Insufficient free space for journals, terminating
2015-05-04T22:03:41.286+0200 [initandlisten] dbexit: 

Mongo's Vagrant VM is such a pain, regarding non-dynamic disk. Is there any way to launch mongods using "smallfiles" option with mlaunch? 
Thx
tivivi63

**Comment by rueckstiess** [comment]
You can pass any option to mlaunch, and if mlaunch doesn't know it, it will check mongod's or mongos's --help text. If it's present there, it will pass it on to that process. You also might want to use --oplogSize if you're worried about disk space: 

So `mlaunch init --replicaset --sharded 3 --smallfiles --oplogSize 300` should work. 

- This feature isn't mentioned in the help text, there's a request to change this: #356 
- It is mentioned in the [mtools wiki](https://github.com/rueckstiess/mtools/wiki/mlaunch)
- See also related open feature request #188 

Thomas

**Comment by rueckstiess** [comment]
I believe this is answered. Closing.
