### ISSUE TITLE
Install m-tools on CentOS 7

### ISSUE THREAD

**Issue by tivivi63** [rueckstiess/mtools#367]
Hello Thomas,

Everything is in the title. :) 

My Mongo cluster is running upon CentOS 7, is there a way to benefit from your tremendous tool on that OS? Is it possible to download package content from Windows and FTP the stuff to CentOS machine ? Are there any dependencies I should be aware of that require the use of install method rather than raw filecopy?

Thanks for the help.
Regards,

**Comment by rueckstiess** [comment]
Theoretically you should be able to install and use mtools on CentOS as well, but I have not had a chance to try it yet (and write install instructions).  

If you have pip available and are connected to the outside world, that's probably the easiest way to install. If that is not an option, next best is to clone the mtools github repo or to copy the folder over, then `cd` into it and run `python setup.py install`, which will put the scripts in the right places. 

Either way you'll have to take care of the dependencies, which can be found [here](https://github.com/rueckstiess/mtools/blob/master/INSTALL.md#additional-dependencies). 

The process will be similar (but obviously slightly different) to the [Ubuntu Installation](https://github.com/rueckstiess/mtools/wiki/mtools-Installation-on-Ubuntu-12.04). I imagine matplotlib could be a problem (required for mplotqueries, the graphical tool).

Hope that helps, let me know if you need any more instructions. It would be tremendously helpful if you get it running and could point me to any gotchas that differed from the Ubuntu installation guide, or even provide a short step-by-step list. :-)
