### ISSUE TITLE
Does mplotqueries  support v3.0+?

### ISSUE THREAD

**Issue by eshujiushiwo** [rueckstiess/mtools#368]
Does mplotqueries  support v3.0+?

**Comment by rueckstiess** [comment]
- MongoDB 3.0+   yes (see [release notes for 1.1.7](https://github.com/rueckstiess/mtools/blob/master/CHANGES.md#version-117), note at that point MongoDB 3.0 was still called 2.8)

- PyMongo 3.x (Python MongoDB driver)   no, not yet, you need to stay at 2.8.x for now.

**Comment by dbachrac** [comment]
I'm trying to use mloginfo and mlogfilter version 1.1.8 against a mongo 3.0.4 log.  It's giving me errors.  Is it supported?

**Comment by dbachrac** [comment]
Do i need to be at python 2.8.x for the current version of mtools 1.1.8 to work with mongo 3.0.4?

  File "/usr/lib/python2.6/site-packages/mtools/mloginfo/mloginfo.py", line 82, in main
    tool.run()
