### ISSUE TITLE
Shutdown sharded nodes in reverse order (compared to startup)

### ISSUE THREAD

**Issue by devkev** [rueckstiess/mtools#369]
Currently nodes are shutdown in (potentially) random order:

https://github.com/rueckstiess/mtools/blob/1.1.8/mtools/mlaunch/mlaunch.py#L422-L433

This makes it possible for the config server to be stopped before the mongos.  If auth is on, this means that the mongos shutdown cannot auth before issuing the `shutdown` command, causing an error such as:

```
Error: cannot authenticate to shut down localhost:11111.
```

Even though there is apparently nothing wrong with auth or the credentials.

**Sharded nodes should be shutdown in reverse order to how they were started up, i.e. mongoses, shard mongods, config mongods.**

**Comment by stennie** [comment]
`mlaunch stop` now uses SIGTERM to shut down instead of trying to keep track of auth topology.
