### ISSUE TITLE
Install mtools on AWS EC2 amazon-linux

### ISSUE THREAD

**Issue by jsherard** [rueckstiess/mtools#370]
Getting the following error:

```
[ec2-user@mongo_huge_page_testing ~]$ pip install mtools
Collecting mtools
  Using cached mtools-1.1.8.tar.gz
Collecting psutil>=2.0 (from mtools)
  Using cached psutil-3.0.1.tar.gz
Installing collected packages: psutil, mtools
  Running setup.py install for psutil
    Complete output from command /usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-JYkmGb/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-fIglw5-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pswindows.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-2.7/psutil
    running build_ext
    building 'psutil._psutil_linux' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/psutil
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_VERSION=301 -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-JYkmGb/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-fIglw5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-JYkmGb/psutil
[ec2-user@mongo_huge_page_testing ~]$ 
```

**Comment by jsherard** [comment]
Figured it out.

Had to install gcc and install mtools as root.

**Comment by gianpaj** [comment]
great to know you resolved the issue

**Comment by tech-cloud-db** [comment]
Hi ,

I am also facing the same issue on Amazon EC2 . i tried after installing gcc but it didnt help me .still facing the issue in installation.



[narendra@mongo mtools-master]$ gcc --version
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[narendra@mongo mtools-master]$ sudo pip install mtools
Requirement already satisfied (use --upgrade to upgrade): mtools in /usr/local/lib/python2.6/site-packages/mtools-1.1.9-py2.6.egg
Downloading/unpacking psutil>=2.0 (from mtools)
  Downloading psutil-3.3.0.tar.gz (261kB): 261kB downloaded
  Running setup.py (path:/tmp/pip_build_root/psutil/setup.py) egg_info for package psutil
    /tmp/pip_build_root/psutil/setup.py:12: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      import atexit
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: manifest_maker: MANIFEST.in, line 18: 'recursive-include' expects <dir> <pattern1> <pattern2> ...
Requirement already satisfied (use --upgrade to upgrade): ordereddict in /usr/lib/python2.6/site-packages (from mtools)
Installing collected packages: psutil
  Running setup.py install for psutil
    building 'psutil._psutil_linux' extension
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_VERSION=330 -I/usr/include/python2.6 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.6/psutil/_psutil_linux.o
    psutil/_psutil_linux.c:12:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python2.6 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ysv3vY-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.6

creating build/lib.linux-x86_64-2.6/psutil

copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.6/psutil

copying psutil/_compat.py -> build/lib.linux-x86_64-2.6/psutil

copying psutil/_psposix.py -> build/lib.linux-x86_64-2.6/psutil

copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.6/psutil

copying psutil/_common.py -> build/lib.linux-x86_64-2.6/psutil

copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.6/psutil

copying psutil/_pswindows.py -> build/lib.linux-x86_64-2.6/psutil

copying psutil/_psosx.py -> build/lib.linux-x86_64-2.6/psutil

copying psutil/__init__.py -> build/lib.linux-x86_64-2.6/psutil

running build_ext

building 'psutil._psutil_linux' extension

creating build/temp.linux-x86_64-2.6

creating build/temp.linux-x86_64-2.6/psutil

gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DPSUTIL_VERSION=330 -I/usr/include/python2.6 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.6/psutil/_psutil_linux.o

psutil/_psutil_linux.c:12:20: fatal error: Python.h: No such file or directory

 #include <Python.h>

                    ^

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python2.6 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ysv3vY-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/psutil
Storing debug log for failure in /root/.pip/pip.log


please help me ....


Thanks,
Narendra

**Comment by aathisankargh** [comment]
@Narendra you have to install python-devel and pymongo package to solve this issue.
```
sudo yum install python-devel
sudo pip install pymongo
```
Thanks
Sankar
