### ISSUE TITLE
mlaunch --auth not working with replica sets

### ISSUE THREAD

**Issue by dhatcher42** [rueckstiess/mtools#380]
Using the follow command will create a standard 3 node replica set but then hang before timing out on creating the authentication user. 

`mlaunch --replicaset --auth`

Error is:

`failed to find a primary, so adding admin user isn't possible`

However, mongo instances are brought up correctly and if you use the mongo shell you can see a primary up and functional.

This was done on a Mac 10.10.4, Mongo 3.0.6, pymongo 3.0.3, and mtools 1.1.9.

**Comment by jeromegn** [comment]
I am facing a similar issue. I'm running mlaunch on 2.4, 2.6, 3.0 and 3.2 and getting that error randomly on any version. Sometimes it works fine, other times it doesn't.

**Comment by Pash10g** [comment]
Hi ,

There is a pull request #414 that suppose to fix that. We will try to integrate it as soon as possible.
