### ISSUE TITLE
LogEvent: Support WriteResult counters like nModified, nInserted, etc.

### ISSUE THREAD

**Issue by zhihuiFan** [rueckstiess/mtools#386]
```
>>> a = '''2015-12-09T01:29:37.597-0700 [conn2068884] update curatedcollection2db.EntryDetail query: { _id: ObjectId(\'5542a016e4b0b6083361c1b1\') } update: { _id: ObjectId(\'5542a016e4b0b6083361c1b1\'), saleEndTime: new Date(1451096398000)} nscanned:1 nscannedObjects:1 nMatched:1 nModified:1 keyUpdates:0 numYields:0 locks(micros) w:1159 170527ms'''
>>> le = LogEvent(a)
>>> le.nscanned
1
>>> le.nupdated
>>> le.nreturned
>>> le.ninserted
>>> le.ndeleted
```

do you have any suggestion on this? 
Actually I want to get the le.nupdated=1 from this since nMatched: 1.

**Comment by rueckstiess** [comment]
Hi, `nupdated` was used in older versions of MongoDB. If you use a newer version, then you are probably looking for `nModified`, see also the documentation on [WriteResult.nModified](https://docs.mongodb.org/manual/reference/method/WriteResult/#WriteResult.nModified).

You can also see in your log line that it has `nModified:1` but no `nupdated:` value. 

Unfortunately, it seems this is not yet supported in mtools. I'll turn this ticket into a feature request to add the WriteResult counters like nModified, nRemoved, nInserted...

**Comment by zhihuiFan** [comment]
Thank you for unbelievable supper fast response.  Before it is supported, I may use the following pattern as a workaround.

>>> re.findall('nMatched:(\d+)', a)

Thanks for your great tools.
