### ISSUE TITLE
RHEL 6 python install fails

### ISSUE THREAD

**Issue by swvanlinge** [rueckstiess/mtools#391]
I'm trying to install mtools 1.1.9 on RHEL 6.  I am not connected to the outside world, so I downloaded the 1.1.9 tar, expanded it out, and then went into the mtools directory and ran "sudo python setup.py install".  I get the following error:

Traceback (most recent call last):
  File "setup.py", line 93, in <module>
    tests_require=test_requires,
NameError: name 'test_requires' is not defined

I don't see anything in the readme advising anything I need to alter out of the box, can you please advise me how to bypass this if possible?  This is being installed on a dev machine that will largely be using it for graphs, so it's ok if other areas don't function 100% if we need to hack the install script a little.

**Comment by stennie** [comment]
Python 2.6 (the default on RHEL/CentOS 6) is end-of-life and no longer supported. We have a note on the wiki for installing Python 2.7 without breaking `yum`: https://github.com/rueckstiess/mtools/wiki/Notes:-Centos-6.
