### ISSUE TITLE
no data to plot. on nscanned/n

### ISSUE THREAD

**Issue by lozjm** [rueckstiess/mtools#398]
> Hi Guys,
> im getting
> {code}
> mplotqueries /data/mongo-esbonlineprod01/mongo-esbonlineprod01.log --type nscanned/n
> 
> ============ ] 97.5 % no data to plot.
> {code}
> but i know i have some COLLSCAN in that log.

any ideas ?

mtools@mtools:/data$ mplotqueries --version
mtools version 1.1.9
mtools@mtools:/data$

**Comment by amitjain10** [comment]
In mtools/mplotqueries/plottypes/scatter_type.py, change line 181 from
```        return getattr(logevent, 'nscanned') and getattr(logevent, 'nreturned')```
to
```        return getattr(logevent, 'nscanned') != None and getattr(logevent, 'nreturned') != None```
then give it another try please.

**Comment by lozjm** [comment]
Thanks you ! – perfect !

Laurence Moughan, Unix Sysadmin & Platform Specialist, Plaform Services, IT
Aer Lingus, Shamrock House, Dublin Airport, Co Dublin, Ireland
T +353 1 886 2299 | www.aerlingus.com<http://www.aerlingus.com/>

**Comment by pukark** [comment]
having the similar issue, have modified the  mtools/mplotqueries/plottypes/scatter_type.py , still does not work

**Comment by stennie** [comment]
@pukark If you are still seeing this problem, can you create a new issue including your versions of mtools, MongoDB server, Python, and a sample log snippet that produces the error?

Thanks,
Stennie
