### ISSUE TITLE
No queries found error

### ISSUE THREAD

**Issue by cameronliam** [rueckstiess/mtools#400]
Hi,
Just installed the tools for the first time, so excuse me if I am making a rookie mistake.

When I run `mloginfo mongodb.log --queries`, I receive the following output:

```
     source: mongodb.log
       host: KDC-UCDMU01:27030
      start: 2016 Feb 07 00:17:05.975
        end: 2016 Feb 10 22:31:07.509
date format: iso8601-local
     length: 463620
     binary: unknown
    version: = 2.6.x (iso8601 format)
    storage: mmapv1

QUERIES

no queries found.
```
Any idea what could cause this, since I know there are queries in the log file:
```
$ cat "mongodb.log" | grep -c "query: {"
27969
```

The only anomaly I see is: `binary: unknown`. Could that be a result of the same problem?
Please advise.
Liam

**Comment by cameronliam** [comment]
So I have confirmed that in 'query_section.py', at line 58:
Both `le.operation` and `le.command` are `None`, any ideas why these values have not been set?

I assume the problem is occurring during the split phase and some weird data in my logs that possibly contains spaces, since the value of `op` in `logevent.py`, at line 393 is always: `mongod.27030[XXXX]:`

**Comment by jimoleary** [comment]
Hi Liam,

I would guess based on ```mongod.27030[XXXX]``` that you are using syslog output. Unfortunately, mtools does not support this format (see https://github.com/rueckstiess/mtools/issues/282).

Is it possible that you can write your logs directly to a mongo log file? The other alternative would be to use something like one of the awk scripts in the #282 to generate output that mtools understands. However, in this case you will have lost some precision related to the time of the events and mtools may not be able to correctly determine the version of mongod from the log line format.
 
-Jim

**Comment by cameronliam** [comment]
In 'logevent.py', at line 393:
The value of `split_tokens` is as follows:
```['2016-02-07T01:02:00.813733+00:00', 'HOSTNAME', 'mongod.27020[30546]:', '[conn26428]', 'query', 'DB.COLLECTION', 'query:', '{', '$and:', '[', '{', 'field', '{', '$in:', '[', '"de55e44de5599bd22221008c"', ']', '}', '},', '{', 'field:', '"value"', '}', '],', 'field:', '"val', 'val', 'val', 'val', 'val', 'val', 'val', 'val', 'val', 'val', 'val', 'val', 'val', 'val', 'val', 'val.",', 'val:', '"val",', 'field:', '"val', 'val",', 'field:', '"val"', '}', 'planSummary:', 'IXSCAN', '{', 'field:', '1,', 'field:', '1,', 'field:', '1,', 'field:', '1', '}', 'ntoreturn:0', 'ntoskip:0', 'nscanned:752110', 'nscannedObjects:53329', 'keyUpdates:0', 'numYields:4', 'locks(micros)', 'r:6134432', 'nreturned:0', 'reslen:20', '3183ms']```

So clearly the 'operation' is not located at `op = split_tokens[self._datetime_nextpos + 1]` as expected.

Where does this problem originate? Is it as a result of custom log output or maybe version differences?

**Comment by cameronliam** [comment]
Sorry, posted before seeing your response. I will investigate generating the correct output, thank you.
