### ISSUE TITLE
mlogfilter and mloginfo not working when invoked from non-TTY context

### ISSUE THREAD

**Issue by tech-cloud-db** [rueckstiess/mtools#404]
getting error like  :this tool can't parse input from stdin.
 when i included  below statement in script 

/usr/local/bin/mlogfilter /mongo/mongodb.log --from "end -24h" > todaymongod.log

/usr/local/bin/mloginfo /mongo/log/mtools/todaymongod.log  --queries >q1.txt

**Comment by rueckstiess** [comment]
Does the same call work from the command line?

Perhaps you need to experiment with quoting values or swapping their order. I'm not that familiar with cron scripts. The same commands on an OS X terminal work for me.

**Comment by tech-cloud-db** [comment]
the same command works for me from  command line.its throwing the error when i scheduled it in cron.

**Comment by rueckstiess** [comment]
I'm sorry you are running into that issue but I don't know how I can help here. It seems to be a problem with executing cron scripts rather than in mtools itself. 

I'll leave this question open for now, perhaps someone else has seen this before and can help.

**Comment by stennie** [comment]
This is the same issue underlying issue as #424:

 - `mloginfo` currently disallows calling from a non-TTY context; you should get an error: "this tool can't parse input from stdin"

 - `mlogfilter` allows calling from a non-TTY context but the positional parameter for the log file is not recognized; you should get an error: "mlogfilter: error: unrecognized arguments"

**Comment by shivrivigo** [comment]
Is this fixed ? I still get same error. Let know if anyone has workaround for the same. Thanks

**Comment by zhugw** [comment]
@shivrivigo 
I also have met this problem when use mloginfo in crontab and from [this post](https://www.codetd.com/article/1579186) I got below workaround 

```
10 0 * * * script -c 'today=`date +\%F`;/bin/mloginfo /tmp/mongodb.log --queries --no-progressbar | /bin/mail -s "mloginfo - ${today}" foo@bar.com'
```
that is wrapped mloginfo inner `script -c  [executable string]`

**Comment by stennie** [comment]
@shivrivigo The GitHub issue is still open, but it looks like wrapping in `script -c` is a suitable workaround (thanks @zhugw!).

**Comment by stennie** [comment]
Changing this behaviour seems far gnarlier than it ought to be, but mtools is generally intended for interactive sessions.

Closing since there is a suitable workaround mentioned above.
