### ISSUE TITLE
inserts and queries format changed in 3.0.9 / 3.1.9 / 3.2.2

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#409]
Recent changes in the server broke log parsing in mtools in various ways. In particular, "mloginfo --queries" and other scripts may not find queries and inserts, depending on the server version. It will take non-trivial effort to make it work again for current and previous versions of MongoDB. Sorry.

Details: 

I've dug around Jira this morning and found the following changes that affect log parsing in mtools: 
- [SERVER-19568](https://jira.mongodb.org/browse/SERVER-19568) changed the log format for queries to the "command" style. mtools currently ignores commands for certain tools (like mloginfo --queries) to avoid double-counting of write operations, because writes used to be logged both as individual operations and as command (one for each bulk op). [DOCS-6259](https://jira.mongodb.org/browse/DOCS-6259) to document this change was closed "won't fix".
- [SERVER-19564](https://jira.mongodb.org/browse/SERVER-19564) removed the log lines for individual insert operations, leaving only the command style (they still exist for updates and deletes though). The ticket does not mention this user-facing change, and this is also nowhere documented. I've just confirmed with Rassi on the kernel team that this ticket is the likely cause for the disappearance of these lines.

So the dilemma for mtools is this: 
- find: now only has command style log lines (was: only operation lines)
- insert: now only has command style log lines (was: both operation and command lines)
- update: has both command and operation lines (no change)
- remove: has both command and operation lines (no change)

To avoid double-counting, mloginfo could now only consider commands and ignore the individual operations (since all major operations now have a "command" version). However, this means no detailed information on individual long-running inserts, updates or deletes as part of bulk operations (we only get 1 command line for each bulk operation). For updates, we would also lose information on how many docs have been updated since that information is missing in the command line:

Operation log line

```
2016-04-12T10:54:12.353+1000 I WRITE    [conn6] update test.foo query: { a: 1.0 } update: { $set: { b: 1.0 } } keysExamined:0 docsExamined:3 nMatched:3 nModified:2 keyUpdates:0 writeConflicts:0 numYields:0 locks:{ Global: { acquireCount: { r: 1, w: 1 } }, Database: { acquireCount: { w: 1 } }, Collection: { acquireCount: { w: 1 } } } 0ms
```

Command log line

```
2016-04-12T10:54:12.353+1000 I COMMAND  [conn6] command test.$cmd command: update { update: "foo", updates: [ { q: { a: 1.0 }, u: { $set: { b: 1.0 } }, multi: true, upsert: false } ], ordered: true } keyUpdates:0 writeConflicts:0 numYields:0 reslen:40 locks:{ Global: { acquireCount: { r: 1, w: 1 } }, Database: { acquireCount: { w: 1 } }, Collection: { acquireCount: { w: 1 } } } protocol:op_command 0ms
```

Note: the Command does not have e.g. "nMatched" and "nModified" fields.

Linking the two lines together to extract information from both is also quite hard, as there is no unique identifier that the two lines share, and they could be thousands of lines apart in a log file. 

An alternative would be to have different strategies for different operations: 
- find / insert use command lines
- update / delete use operation lines

This is a bit hacky but probably the best way forward given the current situation. Unfortunately this only works for current versions, and a lot of logic has to be introduced to maintain backwards-compatibility to previous versions, which will take time and resources, and impact parsing performance.

**Comment by akira-kurogane** [comment]
A quick hack to count COMMAND lines as if they were QUERY or WRITE lines is as follows:

```
diff --git a/mtools/util/logevent.py b/mtools/util/logevent.py
index ba74788..293a931 100644
--- a/mtools/util/logevent.py
+++ b/mtools/util/logevent.py
@@ -393,6 +393,13 @@ class LogEvent(object):
         if op in self.log_operations:
             self._operation = op
             self._namespace = split_tokens[self._datetime_nextpos + 2]
+            if op == "command":
+                #"commmand <ns> command: <find/update/remove/etc.>"
+                cmd_op = split_tokens[self._datetime_nextpos + 4]
+                if cmd_op == "find":
+                    self._operation = "query"
+                elif cmd_op == "remove" or cmd_op == "update" or cmd_op == "insert":
+                    self._operation = cmd_op
```

I.e. it effectively makes 
"COMMAND [conn...] command <ns> command: find" lines -> "QUERY [conn...] find" lines,
and 
"COMMAND [conn...] command <ns> command: <insert/update/remove>" lines -> "WRITE [conn...] <insert/update/remove>" lines, at least so far mloginfo --queries shows.

Of course this leads to double-counting in the log files that have both the legacy QUERY/WRITE op lines and COMMAND lines.

Considering how to do the de-duplication effectively. The 'just-in-time' line and property parsing works against it so far as I can see at the moment.

**Comment by akira-kurogane** [comment]
I don't see a way to work within the paradigm of the current code to de-duplicate log lines of the same operation on a 1-to-1 basis. So instead my idea is to remove duplicate group-by results in mloginfo.

First in logevent:
* Fix the namespace property for COMMAND lines
* Create the pattern for COMMAND lines too.
* (For some reason it seems inserts are excluded, so I don't include them either.)
```
diff --git a/mtools/util/logevent.py b/mtools/util/logevent.py
index ba74788..91e7cb0 100644
--- a/mtools/util/logevent.py
+++ b/mtools/util/logevent.py
@@ -392,7 +392,11 @@ class LogEvent(object):
 
         if op in self.log_operations:
             self._operation = op
-            self._namespace = split_tokens[self._datetime_nextpos + 2]
+            if op == "command":
+                self._namespace = split_tokens[self._datetime_nextpos + 2][0:-4] + split_tokens[self._datetime_nextpos + 7][1:-2]
+            else:
+                self._namespace = split_tokens[self._datetime_nextpos + 2]
+
 
 
 
@@ -405,6 +409,11 @@ class LogEvent(object):
             # trigger evaluation of operation
             if self.operation in ['query', 'getmore', 'update', 'remove'] or self.command in ['count', 'findandmodify']:
                 self._pattern = self._find_pattern('query: ')
+            elif self.command in ['update', 'delete']:
+                self._pattern = self._find_pattern('q: ')
+            elif self.command == 'find':
+                self._pattern = self._find_pattern('filter: ')
+
 
         return self._pattern
```

Then in mloginfo's queries section:
* If a group for "dbfoo.collfoo, op-type, pattern" exists and there is also a "dbfoo.collfoo, command-type, pattern" for the comparable legacy op name v.s. new command name then delete the older-style one. (The pairs are: "update" and "cmd.update", "remove" and "cmd.delete", "query" and "cmd.find")
* (I named the COMMAND lines ones "cmd.<command_type>" deliberately today, but it's debatable if we should do this or not.)

```
diff --git a/mtools/mloginfo/sections/query_section.py b/mtools/mloginfo/sections/query_section.py
index 54050ea..6e2ce23 100644
--- a/mtools/mloginfo/sections/query_section.py
+++ b/mtools/mloginfo/sections/query_section.py
@@ -6,6 +6,7 @@ from mtools.util import OrderedDict
 
 from operator import itemgetter
 from collections import namedtuple
+from sets import Set
 
 try:
     import numpy as np
@@ -58,6 +59,9 @@ class QuerySection(BaseSection):
             if le.operation in ['query', 'getmore', 'update', 'remove'] or le.command in ['count', 'findandmodify', 'geonear']:
                 lt = LogTuple(namespace=le.namespace, operation=op_or_cmd(le), pattern=le.pattern, duration=le.duration)
                 grouping.add(lt)
+            elif le.command in ['find', 'update', 'delete']:
+                lt = LogTuple(namespace=le.namespace, operation="cmd." + op_or_cmd(le), pattern=le.pattern, duration=le.duration)
+                grouping.add(lt)
 
         grouping.sort_by_size()
 
@@ -105,6 +109,20 @@ class QuerySection(BaseSection):
         if self.mloginfo.args['sort'] in ['namespace', 'pattern']:
             reverse = False
 
+        ns_op_ptn_set = Set([(r['namespace'], r['operation'], r['pattern']) for r in table_rows])
+        groups_to_del_set = Set([])
+        for r in table_rows:
+            if r['operation'] == "cmd.find" and (r['namespace'], "query", r['pattern']) in ns_op_ptn_set:
+                groups_to_del_set.add((r['namespace'], "query", r['pattern']))
+            elif r['operation'] == "cmd.update" and (r['namespace'], "update", r['pattern']) in ns_op_ptn_set:
+                groups_to_del_set.add((r['namespace'], "update", r['pattern']))
+            elif r['operation'] == "cmd.delete" and (r['namespace'], "remove", r['pattern']) in ns_op_ptn_set:
+                groups_to_del_set.add((r['namespace'], "remove", r['pattern']))
+
+        trimmed_table_rows = [r for r in table_rows if ((r['namespace'], r['operation'], r['pattern']) not in groups_to_del_set)]
+        if len(trimmed_table_rows) != len(table_rows):
+            table_rows = trimmed_table_rows
+
         table_rows = sorted(table_rows, key=itemgetter(self.mloginfo.args['sort']), reverse=reverse)
         print_table(table_rows, titles, uppercase_headers=False)
         print 
```

Other commands:
_**mlogfilter**_: would need to be changed, but wouldn't be affected straight away by changing logevent.py as shown above. That is, same as before, not fixed for 3.2\+.
_**mplotqueries, mlogvis**_ will include both types of log line events. But it does already right?

Is that right Thomas? Do you see anything else too?

**Comment by glasswalk3r** [comment]
Hello there,

Is the team still looking forward to fix this issue?

I just got the same wrong behavior from mlogfilter:
```

$ mlogfilter slower.log --operation query
$ head slower.log 
2017-05-08T09:21:39.562-0300 I COMMAND [conn22924] command testing.raw_throughput_partial command: find { find: "raw_throughput_partial", filter: { status: "SUCCESS", state: 0, state_ts: { $lte: new Date(1494246060704) }, props.eventType: "scmThroughtputUpstreamPartial" }, sort: { creation_time: 1, _id: 1 }, limit: 100 } planSummary: IXSCAN { state: 1, creation_time: 1, _id: 1 } keysExamined:15130 docsExamined:15130 cursorExhausted:1 numYields:118 nreturned:100 reslen:144229 locks:{ Global: { acquireCount: { r: 238 } }, Database: { acquireCount: { r: 119 }, acquireWaitCount: { r: 1 }, timeAcquiringMicros: { r: 38793731 } }, Collection: { acquireCount: { r: 119 } } } protocol:op_query 38857ms
2017-05-08T09:21:39.750-0300 I COMMAND [conn22881] command testing.raw_throughput_partial command: find { find: "raw_throughput_partial", filter: { status: "SUCCESS", state: { $lte: 8, $gte: 2 }, state_ts: { $lte: new Date(1494245460461) }, props.eventType: "scmThroughtputDownstreamPartial" }, sort: { creation_time: 1, _id: 1 }, limit: 100 } planSummary: IXSCAN { state: 1, creation_time: 1, _id: 1 } keysExamined:98513 docsExamined:98513 hasSortStage:1 cursorExhausted:1 numYields:773 nreturned:7 reslen:10259 locks:{ Global: { acquireCount: { r: 1548 } }, Database: { acquireCount: { r: 774 }, acquireWaitCount: { r: 1 }, timeAcquiringMicros: { r: 38793764 } }, Collection: { acquireCount: { r: 774 } } } protocol:op_query 39288ms
```

I'm using:

```
$ mlogfilter --version
mtools version 1.2.3
```

**Comment by glasswalk3r** [comment]
Hi @stennie, I'm still willing to help with this one... I suggest to add a command line option or set a environment variable to adopt the old behavior. As time passes, people will drop old versions from MongoDB, but mtools can still provide support to old behavior as much time as needed.
Just let me know.

**Comment by stennie** [comment]
Hi @glasswalk3r, thanks for offering to help! We've been discussing how best to address this since the changes aren't entirely straightforward in terms of MongoDB server version (major or minor) and there can also be a mix of lines in the same log file depending on the wire protocol used by the clients. We've been reluctant to make changes without better tests in place so this issue has been lingering for a long while.

@kevinadi and I are wrangling a batch of changes for a 1.3.0 version at the moment and looking at how to approach this issue. A general thought we had in terms of testing sanity would be to create a script which can iterate versions of MongoDB and generate log snippets which can be used to compare mtools' logevent analysis for differences in interpretation. Does that sound like something you might have time to work on? If so, we should break out the test scenarios into a separate GitHub issue.

FYI: to reduce the surface area of what we need to support & test, we are only going to test non End-of-Life versions of MongoDB going forward (so 3.0+) as well as Python 2.7. The older logs have even more strange variations (eg. no years in the timestamps, blank lines, ... ).

Thanks,
Stennie

**Comment by jorge-imperial** [comment]
I have written a Python script to start different versions of mongod, start a javascript script and save the logs.

https://github.com/jorge-imperial/create_mongo_log

**Comment by stennie** [comment]
@jorge-imperial Excellent, thanks for the initiative! Will definitely be helpful to get this issue moving :)

**Comment by glasswalk3r** [comment]
Hello @stennie ,

I didn't know about the wire protocol chosen by the client might change the log format... that's sound crazy!

The best way to deal with it would be able to detect automatically the mongod version and the wire protocol in use to decide how to parse the logs... I really don't know if this kind of detection is even possible. Maybe is it a bug on mongod (not using a standard way for logging)?

I guess we could implement unit testing with the known combinations and implement the code to parse the logs, but I don't know if would be useful if there is a need to identify which combination of version and wire protocol is in use even before running mlogfilter.

**Comment by stennie** [comment]
Closing to clean up the backlog. There isn't a straightforward fix for full accuracy, but the current implementation appears to be Good Enough for diagnostic purposes.

The new [structured logging format](https://docs.mongodb.com/manual/reference/log-messages/#structured-logging) in MongoDB 4.4+ obviates the need to invest more time handling awkward legacy log variations.
