### ISSUE TITLE
mtools 1.2.1 mplotqueries ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by khalidishaq** [rueckstiess/mtools#411]
grep "oplog.rs" ~/APL_MNG_CDW1.log.2016-04-25T00-05-02 | ./mplotqueries 
SCATTER plot
   id   #points  group
    1         1  local.oplog.rs

keyboard shortcuts (focus must be on figure window):

```
       p  switch to pan mode
       o  switch to zoom mode
left/right  back / forward
       h  home (original view)
       l  toggle log/linear y-axis
       f  toggle fullscreen
     1-9  toggle visibility of top 10 individual plots 1-9
       0  toggle visibility of all plots
       -  toggle visibility of legend
     [/]  decrease / increase opacity by 10%
     {/}  decrease / increase opacity by 1%
     </>  decrease / increase marker size
       e  toggle marker edges
       g  toggle grid
       c  toggle 'created with' footnote
       s  save figure
       q  quit mplotqueries
```

_base.py:2817: UserWarning: Attempting to set identical left==right results
in singular transformations; automatically expanding.
left=736078.958658, right=736078.958658
  'left=%s, right=%s') % (left, right))
Traceback (most recent call last):

 File "./mplotqueries", line 9, in <module>

mplotqueries.py", line 604, in main    tool.run()
mplotqueries.py", line 105, in run    self.plot()
mplotqueries.py", line 578, in plot    major, minor, _ = mpl_version.split('.')
ValueError: need more than 1 value to unpack

**Comment by stennie** [comment]
The steps to reproduce this aren't clear and this was reported some time ago; closing to clean up the backlog.

For any future bug reports please also include a log snippet as well as the version of MongoDB used.

Thanks,
Stennie
