### ISSUE TITLE
Need help Not able to start mplotqueries getting below error 

### ISSUE THREAD

**Issue by tech-cloud-db** [rueckstiess/mtools#412]
log]$ mplotqueries  --version
Traceback (most recent call last):
  File "/usr/local/bin/mplotqueries", line 9, in <module>
    load_entry_point('mtools==1.2.1', 'console_scripts', 'mplotqueries')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/mtools/mplotqueries/mplotqueries.py", line 26, in <module>
    raise ImportError("Can't import matplotlib. See https://github.com/rueckstiess/mtools/blob/master/INSTALL.md for instructions how to install matplotlib or try mlogvis instead, which is a simplified version of mplotqueries that visualizes the logfile in a web browser.")
ImportError: Can't import matplotlib. See https://github.com/rueckstiess/mtools/blob/master/INSTALL.md for instructions how to install matplotlib or try mlogvis instead, which is a simplified version of mplotqueries that visualizes the logfile in a web browser.

i have installed the dependencies  stil i am getting the same error .
===========================
log]$ sudo yum install  python-matplotlib
Loaded plugins: priorities, update-motd, upgrade-helper, versionlock
1192 packages excluded due to repository priority protections
Package python26-matplotlib-1.2.0-15.12.amzn1.x86_64 already installed and latest version
Nothing to do

except ,plotqueries i am able to all other tools 
log]$ mlaunch --version
mtools version 1.2.1
 log]$ mlogfilter --version
mtools version 1.2.1
mlogvis --version
mtools version 1.2.1
any help is appreciated 

Thanks

Narendra

**Comment by stennie** [comment]
Hi,

From your output it looks like mtools is using Python 2.7 but the RPM package you are installing is for Python 2.6.

This issue was created a while ago so I'm assuming you've probably found a solution (either installing matplotlib or using `mplotvis`, which does not require it). I'm going to close the issue, but it might help others if you comment here with your solution.

Regards,
Stennie
