### ISSUE TITLE
Cannot do "list" after init

### ISSUE THREAD

**Issue by Steve-Hand** [rueckstiess/mtools#413]
A list after a launch does not work

For example:
$ mlaunch init --data /data/CS-30533 --auth --single --port 28000
launching: mongod on port 28000
 mlaunch list --dir /data/CS-30533/
can't read /data/CS-30533/.mlaunch_startup, use 'mlaunch init ...' first.
 ls -la /data/CS-30533/
total 0
drwxr-xr-x   3 shand  staff  102 May  9 09:19 .
drwxr-xr-x  20 shand  staff  680 May  9 09:13 ..
drwxr-xr-x   6 shand  staff  204 May  9 09:19 data

Apparently the .mlaunch_startup file is not being created

**Comment by rueckstiess** [comment]
you use `--data` in the first line. do you mean `--dir`? that would explain why it doesn't work...

**Comment by Steve-Hand** [comment]
My mistake, I used "data" rather than "dir".
