### ISSUE TITLE
Mlaunch: --arbiter applies to config servers with --csrs

### ISSUE THREAD

**Issue by thatnerd** [rueckstiess/mtools#418]
The following command fails:

`mlaunch init --replicaset --nodes 2 --arbiter --wiredTigerCacheSizeGB 1 --csrs --sharded 3`

but removing either --arbiter or --csrs seems to fix the problem.

**Comment by rueckstiess** [comment]
`--arbiter` should not affect the CSRS replicaset, neither should `--nodes`. CSRS should always be a 3-node replicaset under mlaunch.

**Comment by rueckstiess** [comment]
@stennie, the fix from #421 only addresses `--arbiter` but not `--nodes` yet...

**Comment by Pash10g** [comment]
Hi @rueckstiess ,

I have tested the --nodes and with the input of 2 the number of config servers are still remain 3...

Why did you reopened this issue?

**Comment by Pash10g** [comment]
Ok got @rueckstiess , got it the problem is when the number is higher.

On it.

**Comment by rueckstiess** [comment]
Basically, do the same as you did for `--arbiter` and ignore the any other replicaset arguments (`--nodes`) if extra contains `--configsvr`.

**Comment by rueckstiess** [comment]
As @Pash10g points out, `--nodes` is already adjusted and CSRS will not use it but instead uses `--config` for the number of CSRS nodes. 

Closing this again.
