### ISSUE TITLE
Update OS X matplotlib installation guide for Yosemite & El Capitan 

### ISSUE THREAD

**Issue by stennie** [rueckstiess/mtools#420]
The [matplotlib Installation Guide for Mac OS X](https://github.com/rueckstiess/mtools/wiki/matplotlib-Installation-Guide-for-Mac-OS-X) on the wiki should be updated to mention appropriate installation steps for Yosemite and El Capitan.

**Comment by GETandSELECT** [comment]
I prefer to install that with homebrew. Please also add to Wiki

`brew install homebrew/python/matplotlib # only required for mplotqueries`

**Comment by rueckstiess** [comment]
+1 seems to be much easier too!

**Comment by stennie** [comment]
MacOS Sierra includes `matplotlib` 1.3.1 in the default installation so workarounds no longer required. Huzzah!

Regards,
Stennie
