### ISSUE TITLE
only showing current connections

### ISSUE THREAD

**Issue by dmodica** [rueckstiess/mtools#423]
hi folks.

just a newbie question. i run the following:
mplotqueries /mongo/logs/mongodb.log --type connchurn  --output 1stplot.pdf
and the graph only shows a black line for current connections. it doesnt show the red or blue lines for opened/closed connections. any idea why not ?

thanks

**Comment by rueckstiess** [comment]
I have one theory why that is. It's a guess but worth trying: 

I've noticed in the past that if the bucket size is very small compared to the time covered in the file, then the red/green bars are so thin that they can't be seen. 

To find out if that is the case, can you run the following command?

```
mloginfo /mongo/logs/mongodb.log
```

This will tell you start and end time of the file. The standard bucket size for the conchurn plot is 60 seconds. If the duration covered by the file is in the order of days or weeks, then the bucket size is definitely too small. (For example: 1 day = 24*60 minutes = 1440 buckets, that would probably be less than a pixel per bucket already, depending on the chart size).

You can change the bucket size in `mplotqueries` with the `--bucketsize` parameter. It's in seconds, so perhaps choose 3600 (= 1h buckets) or even larger depending on the duration covered by your log file.

```
mplotqueries /mongo/logs/mongodb.log --type connchurn --bucketsize 3600 --output 1stplot.pdf
```

Hope that fixes the issue. Let me know.

**Comment by dmodica** [comment]
that was exactly it. thanks very much.

**Comment by rueckstiess** [comment]
You're welcome!
