### ISSUE TITLE
Call mTools commands from Node exec

### ISSUE THREAD

**Issue by Nilsaw** [rueckstiess/mtools#424]
This is a basic representation of what I am trying to do.
```javascript
child = exec("mloginfo --help", function (error, stdout, stderr) {
  console.log('stdout: ' + stdout);
  console.log('stderr: ' + stderr);
  if (error !== null) {
    console.log('exec error: ' + error);
  }
});
```

And this is the error that I am getting
`this tool can't parse input from stdin`

I tried putting the complete location of my mloginfo file but the same issue persisted. I understand that the error log is thrown from the mTools library so that confused me as well because I was concerned that the script might not hit the mtools library files.

Any solution to this?

**Comment by stennie** [comment]
@Nilsaw I can confirm the same error: `mloginfo` currently doesn't support calling from a non-tty session.

As a quick test I tried setting [`stdin_allowed=True`](https://github.com/rueckstiess/mtools/blob/develop/mtools/mloginfo/mloginfo.py#L17) in the __init__ method for `mloginfo`. This works for standard arguments (eg `--help`) but does not recognise the positional argument for the log file, which I'm assuming you'd need for this to be useful :).

Example:
```
$ echo "foo" | mloginfo --queries mongod.log
usage: mloginfo [-h] [--version] [--no-progressbar] [--verbose]
                [--connections] [--distinct] [--queries]
                [--sort {namespace,pattern,count,min,max,mean,95%,sum}]
                [--restarts] [--rsinfo] [--rsstate]
mloginfo: error: unrecognized arguments: mongod.log
```

This probably needs to be addressed in the LogFileTool base class ([mtools/util/cmdlinetool.py](https://github.com/rueckstiess/mtools/blob/develop/mtools/util/cmdlinetool.py)) if you want to look into how to fix.

**Comment by stennie** [comment]
This is the same issue as #404, so closing as a duplicate.

**Comment by Nilsaw** [comment]
Thanks for the replying @stennie . Saved me a lot of time.
