### ISSUE TITLE
mtools-1.2.1: `mloginfo --sort`  command needs some docs in Wiki 

### ISSUE THREAD

**Issue by 402309718** [rueckstiess/mtools#425]
I found --sort [namespace,patter,...] does not work  just 

show me   this information below:
     source: mongodb_set.log_online
       host: houndmg1:27017
      start: 2016 Jun 01 23:35:59.168
        end: 2016 Aug 09 15:29:07.466
date format: iso8601-local
     length: 792148
     binary: mongod
    version: 3.0.6
    storage: wiredTiger

so  could u update wiki ,it is so old

**Comment by jimoleary** [comment]
Have you tried something like the following:

```
$ mloginfo --sort count --queries primary.log
```

That works for me.

Note: -**-sort** only works with **--queries**, as  can be seen [here](https://github.com/rueckstiess/mtools/blob/e0e7522600bdab0b1ece14fe55d910ffff8cb423/mtools/mloginfo/sections/query_section.py#L31-L32)

**Comment by stennie** [comment]
@402309718 Thanks for the feedback .. I added a note to the wiki page: https://github.com/rueckstiess/mtools/wiki/mloginfo#queries-section.

The `--sort` parameter should probably validate that `--queries` has also been provided.
