### ISSUE TITLE
mloginfo v 1.2.1 does not detect wiredTiger storage engine default for MongoDB 3.2

### ISSUE THREAD

**Issue by pzoblisein** [rueckstiess/mtools#426]
OS>  mloginfo --version
mtools version 1.2.1

OS> mloginfo rs0.log --rsstate
     source: rs0.log
       host: 127.0.0.1:27017
      start: 2016 Aug 09 13:27:03.332
        end: 2016 Aug 10 14:36:40.204
date format: iso8601-local
     length: 1523196
     binary: mongod
    version: 3.2.6
    storage: mmapv1

Querying the mongo instance itself - shows wiredTiger in use:
rs0:PRIMARY> db.serverStatus().storageEngine;
{
        "name" : "wiredTiger",
        "supportsCommittedReads" : true,
        "persistent" : true
}

Looks like the expression matching in https://github.com/rueckstiess/mtools/blob/develop/mtools/util/logfile.py

match = re.search('engine: "(?P<engine>\S+)"', line)
                if match:
                    self._storage_engine = match.group('engine')
                else: 
                    self._storage_engine = 'mmapv1'

**Comment by stennie** [comment]
@pzoblisein Thanks for the bug report. The current logic does not account for WiredTiger being the default storage engine in MongoDB 3.2.

**Comment by Steve-Hand** [comment]
Fixed with the merging #427
