### ISSUE TITLE
Allow analysis of log files with ctime format

### ISSUE THREAD

**Issue by alexander-marquardt** [rueckstiess/mtools#428]
MongoDB allows log files to output files with ctime format as opposed to iso8601 format, as documented at  https://docs.mongodb.com/manual/reference/configuration-options/#systemLog.timeStampFormat. 

It would be great if mtools could parse files using this format.

**Comment by rueckstiess** [comment]
Hi, have you tried this? mtools already supports all of these time formats. 

If it's not working for you, there may be a different reason. In that case, can you attach some of the log lines that cause problems so I can have a look? (you can redact private data in the lines)

**Comment by alexander-marquardt** [comment]
Hi Thomas,

Thanks for your message. 

I am using mtools 1.2.1 to analyse the log files. 

The log file that it is having problems with has the following format. I will send you an email directly with the complete files.

Wed Jul 13 16:14:35.324 I QUERY    [conn39] getmore rcu.individual_normalized query: { TechnicalHeader.IC_ID: null, TechnicalHeader.NODEDUP_FLAG: true, ContactInfo.Emails.VALIDITY_FLAG: true } cursorid:47273143030 ntoreturn:0 keyUpdates:0 writeConflicts:0 numYields:202 nreturned:10024 reslen:1929777 locks:{ Global: { acquireCount: { r: 406 } }, Database: { acquireCount: { r: 203 } }, Collection: { acquireCount: { r: 203 } } } 220ms

-Alex
