### ISSUE TITLE
MongoDB 3.3+ only supports CSRS for mongos --configdb parameter

### ISSUE THREAD

**Issue by stennie** [rueckstiess/mtools#431]
For MongoDB 3.3+ `mlaunch` should default to CSRS; SCCC is no longer supported.

Currently mlaunch defaults to SCCC and `mongos` will fail to start up:

```
$ mlaunch init --sharded 1 --replica
launching: mongod on port 27018
launching: mongod on port 27019
launching: mongod on port 27020
launching: config server on port 27021
replica set 'shard01' initialized.
launching: mongos on port 27017
can't start process, return code 2.
```

The `mongos` error is:

> BadValue: configdb supports only replica set connection string

**Comment by monkey101** [comment]
Just hit this issue.  There's also no documentation about the --csrs parameter (i had to look at source to find it).  Also, it is possible to have a one node config server replset, which is an option that should be supported I think.

**Comment by monkey101** [comment]
We'll also have to explicitly **disallow** old-style config servers on version > 3.3.3
See: https://jira.mongodb.org/browse/SERVER-22318
