### ISSUE TITLE
add support for automation logs

### ISSUE THREAD

**Issue by GETandSELECT** [rueckstiess/mtools#436]
I really love `mloginfo` and `mlogfilter` as an mongod operator. Please write some command with similar functionality, but for `automation agent` logs. Thank you guys.

**Comment by stennie** [comment]
Thanks for the suggestion! However, `mtools` is specifically for working with MongoDB server logs which have different formats and information than the automation agent logs. There are more than enough changes in the MongoDB server logs for the current team of volunteers to keep up with so closing this suggestion to tidy up the backlog ;-).

Regards,
Stennie
