### ISSUE TITLE
mtools not affiliated to MongoDB? Independent from MongoDB?

### ISSUE THREAD

**Issue by GETandSELECT** [rueckstiess/mtools#440]
I know that MongoDB consultants and MongoDB support uses very much `mtools`.

Is `mtools` completely independent from MongoDB? Please write a few lines about the connection to MongoDB Inc.

![screen shot 2016-08-28 at 09 53 08](https://cloud.githubusercontent.com/assets/10598483/18032486/491fbb1c-6d06-11e6-8634-4134874f3e26.png)

**Comment by stennie** [comment]
`mtools` is an [Apache-licensed](https://github.com/rueckstiess/mtools/blob/develop/LICENSE.md) open source project started by an engineer at MongoDB (Thomas Rueckstiess), and currently resides in his personal GitHub account. As per the disclaimer in the project README.md, `mtools` is not directly supported by MongoDB, Inc: https://github.com/rueckstiess/mtools/blob/develop/README.md#disclaimer.

As you've noted, the tools are popular for users supporting MongoDB deployments (which includes consultants and support engineers). The tools are often referenced in blog posts or webinars about diagnostics and debugging for MongoDB, as log forensics are a powerful aid.

Contribution to `mtools` are very welcome; see: [Contributing to mtools](https://github.com/rueckstiess/mtools/blob/develop/tutorials/contributing.md). Many of the current contributors/collaborators also happen to work at MongoDB (myself included), but are contributing in spare time out of interest in keeping the tools maintained for our own usage.

Changes to the MongoDB server codebase are independent of mtools. For example, see: #409.

Regards,
Stennie
