### ISSUE TITLE
mlaunch --auth does not launch database with "--auth" parameter

### ISSUE THREAD

**Issue by Steve-Hand** [rueckstiess/mtools#446]
mlaunch --auth does not launch database with "--auth" parameter

**Comment by rueckstiess** [comment]
@Steve-Hand can you provide an example what mlaunch does and what you would expect it to do instead? (Note: You can run mlaunch with `--verbose` to see the exact commands it executes)

For replica sets and sharded clusters, the `--keyfile` option is used instead of `--auth`. Is that what you saw?

**Comment by devkev** [comment]
The additional detail being that `--keyfile` implies `--auth`.

**Comment by Steve-Hand** [comment]
Nevermind. Pilot error
