### ISSUE TITLE
mplotqueries default colors could be better

### ISSUE THREAD

**Issue by devkev** [rueckstiess/mtools#453]
The current order is:
- #000000 black
- #00FF00 green
- #0000FF blue
- #FF0000 red
- #01FFFE cyan
- #FFA6FE light magenta
- #FFDB66 yellowish
- #006401 dark green
- #010067 dark blue
- #95003A dark red
- #007DB5 pastel blue
- #FF00F6 magenta
- #FFEEE8 light beige
- #774D00 brown

Since black is used for the edges of the circles in scatterplots, it should never be used for the interior of the circles, because the result is often an indistinguishable black blob.

The first few colours should not be green or red, since these have good/bad connotations, and will always appear "the most" on plots.  So it'd be best to start with some "neutral" colours, like blue, magenta, cyan, before resorting to red and green.

White can't be used since it's the background color.  However it would be possible to have 1 or 2 shades of grey (eg. #808080, or #555555 and #AAAAAA, or #3f3f3f and #bdbdbd).

After this can come the rest of the existing colors.

So the suggestion is to have:
- #0000FF blue
- #FF00F6 magenta
- #01FFFE cyan
- #bdbdbd light gray
- #3f3f3f dark gray
- #FF0000 red
- #00FF00 green
- #FFA6FE light magenta
- #FFDB66 yellowish
- #006401 dark green
- #010067 dark blue
- #95003A dark red
- #007DB5 pastel blue
- #FFEEE8 light beige
- #774D00 brown

**Comment by rueckstiess** [comment]
I thought I did my due diligence going through http://stackoverflow.com/questions/309149/generate-distinctly-different-rgb-colors-in-graphs (mostly answer 2). 

:-)

I understand the reasoning/issues with black. Ok. (But we'd lose one highly distinct color). 

I'd rather not sacrifice red and green because of bad connotations since they are very distinctly different colors. Colors further down on the list are closer in the color space and less easily distinguishable. I don't care enough to argue on this point though. 

Having the two gray tones so high up the list and next to each other is a mistake imo.

Since you seem to care enough about the colors, why don't you try a few different color orderings and plot a typical scatter plot with mplotqueries and share the screenshots here? And then we can let people vote? :-)

**Comment by devkev** [comment]
Will do.

I could easily be convinced to have red and green earlier in the list.

I could also be sold on simply replacing black with dark grey, and shifting it to be after the first few colours.  "White" could then be simulated by light grey, and could be a bit further down the list.

**Comment by braz** [comment]
Moving this as had missed this issue.

I'd be very conscious of colour blindness when suggesting red. Blue -> Green spectrum is much more friendly in these cases.
http://www.cs.ubc.ca/~tmm/courses/547-15/#chap10 particularly http://www.personal.psu.edu/faculty/c/a/cab38/ColorSch/ASApaper.html

Checkout these simulators:
http://rehue.net/
http://www.color-blindness.com/
http://www.etre.com/tools/colourblindsimulator/

**Comment by devkev** [comment]
Wow, how has it been 3 months already?! :/

The sample plots below nicely demonstrate the "big black blob" effect, where it's possible to see the difference in "density" when blue is used instead.  But it doesn't show much else.  I'm still in the process of looking for another sample logfile which better shows the changes in the first ~6 colors.

## Sample plot, current color scheme:
![before-linear](https://cloud.githubusercontent.com/assets/1083020/21671359/0dcec8d0-d36f-11e6-9086-acffa56f5caf.png)

## Sample plot, proposed color scheme:
![after-linear](https://cloud.githubusercontent.com/assets/1083020/21671366/1bfdb704-d36f-11e6-924a-6161bf36ed36.png)

## Same plot but log scale, current color scheme:
![before-log](https://cloud.githubusercontent.com/assets/1083020/21671415/6bf53e76-d36f-11e6-9e52-4e6270f822e5.png)

## Same plot but log scale, proposed color scheme:
![after-log](https://cloud.githubusercontent.com/assets/1083020/21671401/5cad3ba8-d36f-11e6-902c-882bc207c3c0.png)

**Comment by devkev** [comment]
Okay, here are some further images.  With the current color scheme, my brain can't help but associate "goodness" / "acceptability" to the green dots, and "badness" / "undesirableness" to the red dots.  I worry that others might be the same.  This is an issue because green and red are 2nd and 4th in the current list of colors, making them more likely to be present and prominent in plots.  I don't mind them being there, but I think they should be lower down so they're less likely to prominent in the plot.


## Sample plot, current color scheme:

![before-legend-safe-annot](https://cloud.githubusercontent.com/assets/1083020/21706165/1f4829bc-d419-11e6-8964-16239edc22dc.png)


## Sample plot, proposed color scheme:

![after-legend-safe](https://cloud.githubusercontent.com/assets/1083020/21706182/302f2f64-d419-11e6-9b1e-67530a245ab3.png)


## Sample plot, tweaked proposed color scheme:

The grays were chosen to be 25% and 75%, but in the above plot I find that there isn't really enough contrast between the light gray and the white background.  So I tweaked the grays to be 5/16 (#505050) and 9/16 (#909090), and to put the darker one first.  I like this plot the best of all.  I like that the most prominent colors are "neutral" (in my head) yet still distinct.  I've updated the PR with the commit to adjust the grays.

![after-swapped-darker-grey-legend-safe](https://cloud.githubusercontent.com/assets/1083020/21706198/43864b42-d419-11e6-9aaa-f7842d968925.png)


## Color blindness

I ran these images through some of the color blindness simulators, for the most common forms of color blindness.  I was going to post them here, but it now feels like scope creep - as I was looking at them I got the impression that it's too hard (and maybe impossible) to optimise for everything all at once.  So my feeling is that color blindness would best be addressed by a separate feature that allows a customisable or selectable color scheme.  So I've opened #475 for that.
