### ISSUE TITLE
bson package should be included in requirements.txt

### ISSUE THREAD

**Issue by mhelmstetter** [rueckstiess/mtools#463]
requirements.txt does not include the bson package. When running mgenerate I get the following error:

ImportError: No module named bson

**Comment by rueckstiess** [comment]
Thanks, but please use the the standalone mgeneratejs from now on. It's a full replacement for mgenerate: faster and more features/operators. 

```
npm install -g mgeneratejs
```

We'll deprecate mtools' mgenerate soon.
