### ISSUE TITLE
numpy should be included in requirements.txt

### ISSUE THREAD

**Issue by mhelmstetter** [rueckstiess/mtools#464]
When numpy is not present the 95th% column will show as "n/a"

numpy should be included in requirements.txt.

**Comment by rueckstiess** [comment]
Numpy is a huge dependency and it should not be required to run

**Comment by stennie** [comment]
With mtools 1.2.4 it will be possible to try to install some or all extra dependencies via `pip`: https://github.com/rueckstiess/mtools/blob/develop/INSTALL.md#additional-dependencies.
