### ISSUE TITLE
Remove support for Python 2.6

### ISSUE THREAD

**Issue by kevinadi** [rueckstiess/mtools#469]
Python 2.6.0 was [released in 2008](https://www.python.org/download/releases/2.6/), with the final binary release (2.6.6) in [Oct 2013](https://www.python.org/download/releases/2.6.6/). Currently it is [retired and thus unsupported](https://www.python.org/download/releases/2.6.9/).

New tests for mlaunch are written for Python 2.7, and builds are currently failing due to travis-ci testing for 2.6 and 2.7 (PR #468). Note that the tests are passing in 2.7.

I propose removing support for Python 2.6, which is way outdated anyway.

**Comment by stennie** [comment]
It's getting harder to set up a test environment for Python 2.6, but RHEL6 seems to be the main motivation: #477. I suggest adding a wiki page with instructions on how to install Python 2.7 in RHEL6 before removing Python 2.6 from test considerations.
