### ISSUE TITLE
mlaunch needs modifications to launch sharded clusters in MongoDB 3.4

### ISSUE THREAD

**Issue by alexander-marquardt** [rueckstiess/mtools#474]
Using mlaunch with MongoDB 3.4 will require the following changes:
-  shard nodes are launched with the --shardsvr option. 
- (I believe) config servers must be launched as a replica set, even if it is a single node 
- (I believe) mongos must specify --configdb with a replica set name defined

**Comment by rueckstiess** [comment]
Hi @alexander-marquardt what version are you running? We believe all these points have been addressed in [version 1.2.3](https://github.com/rueckstiess/mtools/blob/release-1.2.3/CHANGES.md), released Dec 14. Let us know if that is not the case.

You can upgrade with `sudo pip install mtools --upgrade`.

**Comment by alexander-marquardt** [comment]
I was running an older version. Upgrading fixed the issue. Sorry about the false bug.

Thanks!

**Comment by rueckstiess** [comment]
No prob
