### ISSUE TITLE
Running mtools with Python 2.6 (Centos6)

### ISSUE THREAD

**Issue by bimalkharel** [rueckstiess/mtools#477]
```
Traceback (most recent call last):
  File "/usr/bin/mlaunch", line 11, in <module>
    load_entry_point('mtools==1.2.3', 'console_scripts', 'mlaunch')()
  File "/usr/lib/python2.6/site-packages/mtools/mlaunch/mlaunch.py", line 1438, in main
    tool.run()
  File "/usr/lib/python2.6/site-packages/mtools/mlaunch/mlaunch.py", line 260, in run
    getattr(self, self.args['command'])()
  File "/usr/lib/python2.6/site-packages/mtools/mlaunch/mlaunch.py", line 319, in init
    self._start_on_ports(nodes, wait=True, overrideAuth=True)
  File "/usr/lib/python2.6/site-packages/mtools/mlaunch/mlaunch.py", line 1131, in _start_on_ports
    ret = subprocess.check_output([command_str], stderr=subprocess.STDOUT, shell=True)
AttributeError: 'module' object has no attribute 'check_output'
```
CentOS release 6.8 (Final)
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)

Is CentOS 6 still supported with the default Python? Any changes I need to make?

**Comment by stennie** [comment]
@bimalkharel Thanks for the bug report. The `subprocess.check_output` method was added in Python 2.7 so we'll need to add a workaround for Python 2.6.

The first usage of this method is in mtools 1.2.3, so until this is fixed you might be able to use mtools 1.2.2 if you are using MongoDB 3.2 or older. FYI, the main change theme for mtools 1.2.3 was adding support for MongoDB 3.4 in `mlaunch`: https://github.com/rueckstiess/mtools/blob/develop/CHANGES.md#version-123.

**Comment by stennie** [comment]
Note: development support for Python 2.6 ended in October, 2013 with the 2.6.9 release: https://mail.python.org/pipermail/python-dev/2013-September/128287.html.

I appreciate Python 2.6 is the default with CentOS 6, but it would probably be preferable to install Python 2.7 for broader support.

**Comment by bimalkharel** [comment]
@stennie Hi Stephen, thanks for the clarification. I tried and apparently succeeded in installing 2.7 but even after creating a "python" alias to point to the usr installed version, mtools defaulted to 2.6 (which apparently should not be removed because yum depends on it). Did I not use the correct install method? (I tried three ways - 1. build and install from source (found that SSL and zlib were not built), 2. used SCL and 3. Tracked down prebuilt rpm and tried to install that)

**Comment by stennie** [comment]
@bimalkharel Apologies for missing your last comment here. Installing Python 2.7 via SCL should be the right approach for RHEL/CentOS 6, and we've added a wiki note after testing this: https://github.com/rueckstiess/mtools/wiki/Notes:-Centos-6.

This appears to work fine and we have decided to stop supporting/testing Python 2.6 as it is well past End-of-Life. I'm assuming you were able to work out your issue with Python 2.7, but if you have any tips to share please let us know.

Regards,
Stennie
