### ISSUE TITLE
util/pattern.py line 15 wrong indentation level

### ISSUE THREAD

**Issue by yxdong** [rueckstiess/mtools#478]
line 15 of util/pattern.py, the sentence  " rv = sorted(rv)" is better to put outside of the for loop

**Comment by kevinadi** [comment]
Here's the line in question: https://github.com/rueckstiess/mtools/blob/develop/mtools/util/pattern.py#L15

Looks as described, the line `rv = sorted(rv)` should be able to be unindented without altering the result of the function.
