### ISSUE TITLE
State in the README that mlaunch is not supported on Windows.

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#480]
See issue #479.

It should be clearly stated in the main README that mlaunch does not work on Windows.

**Comment by stennie** [comment]
In addition to mentioning in the README, perhaps there could be more proactive notification if it is possible to detect Windows and warn during either of:
 * `mtools` installation
 * when running `mlaunch`

**Comment by stennie** [comment]
We have PR #488 for windows support, so this caveat will no longer be necessary with mtools 1.2.4 or newer.
