### ISSUE TITLE
Fields do not render in the same order as listed in the template.

### ISSUE THREAD

**Issue by dgajohnson** [rueckstiess/mtools#481]
So this...

`{
    "user": {
      "a": "$number",
      "b": "$number",
      "c": "$number",
      "d": "$number",
      "e": "$number",
      "f": "$number"
    }
}
`

renders as 

`
> db.mgendata.findOne()
{
	"_id" : ObjectId("589a3d10c40dc61ae7544378"),
	"user" : {
		"a" : 8,
		"c" : 63,
		"b" : 41,
		"e" : 28,
		"d" : 20,
		"f" : 39
	}
}`

Notice the order of fields are not maintained.

**Comment by rueckstiess** [comment]
Hi. We are going to deprecate `mgenerate` in the next version of mtools. Please use the new implementation `mgeneratejs`, which is a standalone tool written in Node.js. It is faster and offers more features. 

https://github.com/rueckstiess/mgeneratejs

Download and usage instructions are in the README.
