### ISSUE TITLE
Tune default WT cache size

### ISSUE THREAD

**Issue by tap1r** [rueckstiess/mtools#512]
Granted that most uses for `mlaunch` are for reproduction cases and attach to `localhost`, can I recommend that the default value for `--wiredTigerCacheSizeGB` be set to a very conservative value.  I would suggest either the minimum (256MB) or another low default (1GB).

Alternatively, when initialising replsets/clusters, divide the default cache size (50% of RAM or some other lower value) by the number of nodes to prevent RAM oversubscription by the cumulative WT caches.  For example:

- WT cache = RAM * 0.5 / nodes * 2

or 

- WT cache = 256MB

**Comment by stennie** [comment]
Thanks @tap1r, that's a good suggestion. In MongoDB 3.0 and 3.2 the minimum is 1GB; in 3.4 the minimum has been lowered to 256MB (and `--wiredTigerCacheSizeGB` can be specified as a float).

I think our safe choice would be a 1GB default if the storage engine is WiredTiger and `--wiredTigerCacheSizeGB` hasn't been specified on the command line.

FYI, you can currently pass through your preference as an extra option to `mlaunch`. Any options that `mlaunch` doesn't handle are passed to the binary if listed in `mongod --help`, eg:

> mlaunch init --replica 3 --wiredTigerCacheSizeGB 1

**Comment by kevinadi** [comment]
I will also mention that custom parameters passed to `mlaunch` will be recorded in `.mlaunch_startup`, so that doing `mlaunch stop` then `mlaunch start` will preserve the custom parameters.

**Comment by stennie** [comment]
Fixed in PR #517
