### ISSUE TITLE
Fix Readme rendering on PyPI

### ISSUE THREAD

**Issue by kallimachos** [rueckstiess/mtools#521]
Currently, PyPI does not support Markdown. As a result, the [description for mtools](https://pypi.python.org/pypi/mtools) is not rendered correctly.

I suggest one of two fixes:

- convert `README.md` to reStructuredText, which renders correctly on both PyPI and GitHub
- specify the [Description-Content-Type](https://packaging.python.org/specifications/#description-content-type) as `text/markdown` in `setup.py` using [long_description_content_type](https://github.com/pypa/setuptools/pull/1075). Note this option has not yet been implemented in [readme_renderer](https://github.com/pypa/readme_renderer), so currently will not work.

I'm happy to do the conversion work if that is the preferred path.

**Comment by stennie** [comment]
> convert README.md to reStructuredText, which renders correctly on both PyPI and GitHub

One format to rule 'em both would be great!

Thanks,
Stennie
