### ISSUE TITLE
.local resolution of local machine on McOS Sierra is disabled.

### ISSUE THREAD

**Issue by idansworld** [rueckstiess/mtools#526]
.local resolution of local machine on Sierra is disabled. This means that commands like rs.initiate() on a local host fails.

Currently a workaround I found is to activate any of the filesharing options on the mac. However, this is should not be the formal way to address this as this is a security risk.

**Comment by stennie** [comment]
@idansworld Can you confirm the version of `mlaunch` and command line you are using?

Thanks,
Stennie

**Comment by idansworld** [comment]
Command line is: mlaunch init --replicaset 3 --dir data
fails on:
"
No host described in new configuration 1 for replica set replset maps to this node  - will retry
No host described in new configuration 1 for replica set replset maps to this node  - will retry
"
Mlaunch version was 1.2.3, I did not realize the upgrade to 1.3.0 failed when I ran it yesterday, I reinstalled mtools from scratch to 1.3.0 and now it works using "localhost".

Thank you Stennie.
