### ISSUE TITLE
via ssh  to exec mlogfilter  ,find the error  ：unrecognized arguments: /home/data/mongodb/log/log

### ISSUE THREAD

**Issue by smfor** [rueckstiess/mtools#529]
such as the title saids, when i try to ssh to run the mlogfilter of  remote PC

like : ssh root@10.1.1.1  "mlogfilter /home/data/mongodb/log/log --slow 10000 --json --from today"

then comes the error ：
mlogfilter: error: unrecognized arguments: /home/data/mongodb/log/log

thank you !
 

| Software         | Version
| ---------------- | -------
| mtools           | 1.3.1
| MongoDB server   | 3.4 
| Operating system |

**Comment by stennie** [comment]
@smfor Thanks for the bug report. This is actually the same issue as #404 (`mlogfilter` doesn't currently doesn't support non-TTY contexts) so I'm closing as a duplicate.

With `ssh` a workaround should be to add the `-t` parameter to force psuedo TTY allocation, eg:

    ssh -t root@10.1.1.1 "mlogfilter /home/data/mongodb/log/log --slow 10000 --json --from today"

Alternatively (and less conveniently) you could login to the server to run the command interactively.

Regards,
Stennie

**Comment by smfor** [comment]
thank you for so quickly response，it's ok now , best regards !

**Comment by smfor** [comment]
@stennie ,thank you for so quickly response，it's ok now , best regards !
