### ISSUE TITLE
mlaunch: check on launch if dbpath exists

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#53]
If the dbpath exists already (from previous mlaunch), then compare the startup options. If they are different, exit with warning that existing data will be overwritten and that `mlaunch --restore` should be used to restart. 

Should we allow the script to run if the same number of nodes are started? What about with a different number of mongos? more shards?

Perhaps offer `--force` to force overwrite.

**Comment by stennie** [comment]
This issue describes behaviour of `mlaunch` pre-#148. `mlaunch --restore` no longer exists and `mlaunch start` will report "A different environment already exists" if you try to init into an existing environment.
