### ISSUE TITLE
Test logging changes/compat for MongoDB 3.6

### ISSUE THREAD

**Issue by stennie** [rueckstiess/mtools#532]
It's possible that there may be logging changes in MongoDB 3.6 (in addition to changes identified in #409, #473) that may cause compatibility issues with log parsing.

**Comment by stephentunney** [comment]
It's worth pointing out there will be changes to timestamps in replication logs - SERVER-27814
I'm not sure if this change will affect current functionality in mloginfo/mlogfilter

**Comment by stennie** [comment]
mtools isn't parsing timestamps for replication so SERVER-27814 doesn't have any impact.

Since there haven't been any other reported 3.6 issues after more than 2 years, I'm going to close this todo issue.
