### ISSUE TITLE
Add support for audit log parsing in JSON format

### ISSUE THREAD

**Issue by tap1r** [rueckstiess/mtools#533]
*mtools* does not currently support JSON formatted logs, as generated by the _mongod_ [auditLog](https://docs.mongodb.com/manual/reference/configuration-options/index.html#auditLog.destination) option
 
### Expected behaviour
I would expect parity behaviour with the standard _mongod.log_ format

### Actual/current behaviour
Attempting to parse a JSON syslog seems to leave _mplotqueries_ in an endless loop.
Parsing with _mloginfo_:
```text
     source: json.log
       host: unknown
      start: unknown
        end: unknown
date format: None
     length: 1966
     binary: unknown
    version: unknown
    storage: unknown
```

**Comment by stennie** [comment]
Audit logs contain different information from the `mongod` / `mongos` logs and are not supported at the moment.

However, `mplotqueries` should not loop indefinitely. Can you confirm `mplotqueries --version`? A sanity check was added in 1.3.1 which should cause tools to return gracefully if a file doesn't appear to be a supported format.

Thanks,
Stennie

**Comment by stennie** [comment]
Confirmed that mtools 1.3.1 doesn't loop indefinitely:

> Error: <json-auditLog.log> does not appear to be a supported MongoDB log file format

However, could be useful to unpack relevant entries from the JSON audit logs created by MongoDB Enterprise.

**Comment by tap1r** [comment]
Confirmed, v1.3.1 does not exhibit the looping issue.  Some nominal support for the JSON format would still be desired, even if the log schema is different

**Comment by stennie** [comment]
JSON audit logs have different formatting & fields from MongoDB logs, so this seems best suited for a separate tool. The log parsing libraries shared by `mtools` assume MongoDB server logs and metrics.

Regards,
Stennie
