### ISSUE TITLE
JavaScript test file to generate example logs for cross-release testing: core

### ISSUE THREAD

**Issue by stennie** [rueckstiess/mtools#534]
Create a JavaScript file with a set of queries and commands useful for comparing log parsing across different releases of MongoDB. This should cover core commands that would apply to any MongoDB deployment: inserts, updates, findAndModify, bulk writes, indexes (collection scan, index scan, ..), fast counts, count with criteria, etc.

The goal is to:
 - use [`create_mongodb_logs`](https://github.com/jorge-imperial/create_mongodb_logs) to generate test logs for all supported releases of MongoDB server
 - write a test suite invoking mtools' `util/logevent.py` to extract and compare metrics from the logs
 - identify variations in logging (eg. #409) and raise tracking issues to work out how to handle these

**Comment by jorge-imperial** [comment]
I can take this.

**Comment by stennie** [comment]
Closing as a #wontfix: the surface area of parsing is significantly reduced by structured logging in MongoDB 4.4+: https://docs.mongodb.com/manual/reference/log-messages/
