### ISSUE TITLE
Update log2code data for MongoDB 3.0+

### ISSUE THREAD

**Issue by stennie** [rueckstiess/mtools#537]
The `log2code.pickle` data used by `mloginfo --distinct` needs to be updated for current versions of MongoDB. This was last updated for 2.6.0-rc1 (!).

**Comment by rueckstiess** [comment]
@stennie the tool to extract the log lines and write the log2code.pickle file is under `mtools/util/parse_sourcecode.py`. You'd need to adjust the constants at the top to point to your checked out mongodb repo. Also, no guarantees that this is still working after the mongo code was refactored :-)
