### ISSUE TITLE
Getting TypeError while I am executing mlaunch in my vagrant box

### ISSUE THREAD

**Issue by osmanddas** [rueckstiess/mtools#572]
I am taking 'M310: MongoDB Security' course from MongoDB University. As instructed, I am supposed to use mlaunch utility to create a sharded cluster. While running the command I am getting TypeError as given below:

**vagrant@database:~$ mlaunch init --auth --sharded 3 --replicaset --nodes 3 --config 3** 
launching: mongod on port 27018
launching: mongod on port 27019
launching: mongod on port 27020
launching: mongod on port 27021
launching: mongod on port 27022
launching: mongod on port 27023
launching: mongod on port 27024
launching: mongod on port 27025
launching: mongod on port 27026
launching: config server on port 27027
launching: config server on port 27028
launching: config server on port 27029
replica set 'shard01' initialized.
replica set 'shard02' initialized.
replica set 'shard03' initialized.
launching: mongos on port 27017
adding shards. can take up to 30 seconds...
Traceback (most recent call last):
  File "/usr/local/bin/mlaunch", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/mtools/mlaunch/mlaunch.py", line 1622, in main
    tool.run()
  File "/usr/local/lib/python2.7/dist-packages/mtools/mlaunch/mlaunch.py", line 319, in run
    getattr(self, self.args['command'])()
  File "/usr/local/lib/python2.7/dist-packages/mtools/mlaunch/mlaunch.py", line 528, in init
    self.restart()
  File "/usr/local/lib/python2.7/dist-packages/mtools/mlaunch/mlaunch.py", line 778, in restart
    processes = self._get_processes()
  File "/usr/local/lib/python2.7/dist-packages/mtools/mlaunch/mlaunch.py", line 1355, in _get_processes
    name = p.name()
TypeError: 'str' object is not callable
 
### Expected behavior
I shouldn't get any TypeError

### Actual/current behavior
Getting TypeError

### Steps to reproduce the actual/current behavior
Given above

### Environment

| Software         | Version
| ---------------- | -------

1. **MongoDB** shell version: 3.2.18
2. vagrant@database:~$ **python**
    Python 2.7.12 (default, Jul 18 2016, 15:02:52) 
    [GCC 4.8.4] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> 
3. **mtools** version 1.3.2

**Comment by stennie** [comment]
@osmanddas Thanks for the bug report! This is possibly the same issue as #569, which so far doesn't seem to be trivially reproducible.

There are a few Vagrant images used in M310 and MongoDB University: can you confirm which image you used and the O/S version?

Can you also confirm the version of `psutil` you have installed with:

     python -c "import psutil; print psutil.__version__"

Regards,
Stennie

**Comment by ashrafakl** [comment]
The same issue with me
The psutil version is 1.2.1
Vagrant Database Box configuration:

    database.vm.box = "ubuntu/trusty64"
    database.vm.hostname = "database.m310.mongodb.university"
    database.vm.provision :shell, path: "provision-database", args: ENV['ARGS']`

**Comment by ashrafakl** [comment]
@stennie @osmanddas 
This issue has been resolved after removing psutil version 1.2.1 and  installing version 5.4.3.

Regards
Ashraf

**Comment by stennie** [comment]
Looks like this was due to a missing `psutil` dependency (#557) which has been corrected in the latest version of mtools (upcoming 1.4.0). The original dependency was `psutil` >= 2.0.0, so 1.2.1 was definitely too old.

If you are still encountering this issue in mtools >= 1.4.0 please open a new bug report.

Thanks,
Stennie
