### ISSUE TITLE
mtools RPM package request

### ISSUE THREAD

**Issue by armanid27** [rueckstiess/mtools#577]
### Environment

| Software         | Version
| ---------------- | -------
| mtools           | 
| MongoDB server   | 
| Operating system |

**Comment by stennie** [comment]
Thanks for the suggestion, @armanid27. `mtools` packages are currently only published via the standard [PyPi](https://pypi.python.org/pypi/mtools/) repository.

Which O/S version are you looking for RPM packages for? Does your deployment environment have any specific limitations that prevent using the PyPi installation?

Regards,
Stennie

**Comment by stennie** [comment]
There are no current plans to test or maintain RPM packages, so closing this issue to tidy up the backlog.

Regards,
Stennie
