### ISSUE TITLE
Support path parameters (binarypath, dbpath, logpath) containing spaces

### ISSUE THREAD

**Issue by jsmurphy** [rueckstiess/mtools#578]
`mlaunch` does not currently support Windows paths that contain spaces. The only way to get it to work is to ensure that the binary path, db path and log path do not contain any spaces.

We [split up the command line using space as the delimiter](https://github.com/rueckstiess/mtools/blob/develop/mtools/mlaunch/mlaunch.py#L1607), and do not take double quotes into account.
 
### Expected behavior
Binary path, db path and log path should all be able to contain spaces.

### Actual/current behavior
Presently what happens is that mlaunch fails with the following output:
```
PS D:\development\mtools> mlaunch init --sharded 3 --replicaset --config 3 --mongos 2 --binarypath="C:\program files\mongodb\server\3.2.10-Enterprise"
The system cannot find the file C:\program.
None

can't start process, return code 1. tried to launch: start /b C:\program files\mongodb\server\3.2.10-Enterprise\mongod --replSet shard01 --dbpath D:\\development\\mtools\\data\\shard01/rs1\\db --logpath D:\\development\\mtools\\data\\shard01/rs1\\mongod.log --port 27019  --shardsvr --wiredTigerCacheSizeGB 1
```

### Steps to reproduce the actual/current behavior
Use a `mongod` binary that exists in a directory that contains a space, such as `C:\program files\mongodb\server\3.2.10-Enterprise`.

### Environment
Windows Server 2016

**Comment by devkev** [comment]
Just a reminder that Linux/MacOS can easily have spaces in paths also.  So even though this will be more prevalent on Windows, it's not specific to Windows.
