### ISSUE TITLE
mlogvis and nscanned: restrict to collection scan?

### ISSUE THREAD

**Issue by gboysko** [rueckstiess/mtools#614]
Right now, when using the mlogvis tool to chart "nscanned" on the y-axis, the scan count includes key scans as well as collection/document scans (as far as I can tell).

I found this unexpected and wanted the tool to highlight the number of documents scanned. For example, covered queries shouldn't really raise concern (from a performance POV) as the index supplies all of the data.

### Expected behavior
Only restrict nscanned to include documents scanned (and not keys scanned).

### Actual/current behavior
nscanned shows the number of keys or documents scanned.

### Steps to reproduce the actual/current behavior
Simply run queries that are resolved against an index.

**Comment by stennie** [comment]
There are different scan values for documents examined versus index entries. The mtools names are based on historical parameters in MongoDB explain/log results:

- `nscanned` is the number of index entries (aka [`totalKeyExamined`](https://docs.mongodb.com/manual/reference/explain-results/#explain.executionStats.totalKeysExamined) in modern MongoDB explain results)

- `nscannedObjects` is the number of documents examined (aka [`totalDocsExamined`](https://docs.mongodb.com/manual/reference/explain-results/#explain.executionStats.totalDocsExamined) in modern MongoDB explain results)

There is also `n` (aka [`nReturned`](https://docs.mongodb.com/manual/reference/explain-results/#explain.executionStats.nReturned) in modern explain results) which is the number of matching documents. A typical query for index efficiency is comparing the ratio of `nscanned/n` (for example `mplotqueries --type nscanned/n ...`).

The `mlogvis` grouping option for `nscanned` is currently only showing index key scans. It would be more useful to replace this with `nscanned/n`, but `mlogvis` is currently a simple visualisation without any derived metrics.

Is there a reason you are unable to use the full `mplotqueries`?

If you are only interested in collection scans or inefficient queries you can filter the logs before visualising:

- `mlogfilter mongod.log --planSummary COLLSCAN | mlogvis` # plan summary indicates collection scan
- `mlogfilter mongodb.log --scan | mlogvis`  # only output lines with [poor index usage](http://blog.rueckstiess.com/mtools/mlogfilter.html#collection-scans)

Regards,
Stennie

**Comment by gboysko** [comment]
Thanks @stennie. I am new to the tools and this was helpful. I was using `mlogvis` as it allowed me more interactive discovery of the data.

Regarding `--scan`, it has limitations in that the total number of keys needs to be at least 10,000. I was just testing a smaller dataset and didn't reach that minimum.
