### ISSUE TITLE
Is it possible to start replset with writeConcernMajorityJournalDefault: false?

### ISSUE THREAD

**Issue by igorsol** [rueckstiess/mtools#622]
This is a question, not issue.

Using mlaunch is it possible to start replica set with `writeConcernMajorityJournalDefault` set to false?
This option should be provided in replicaset configuration document. I know no command line analog.

**Comment by stennie** [comment]
@igorsol As you've noted, `writeConcernMajorityJournalDefault` is part of the replica set configuration so you would have to change this value after starting up a replica set. `mlaunch` currently does not do any generic post-startup reconfiguration.

The value can be changed at runtime (without a restart).

Regards,
Stennie

**Comment by igorsol** [comment]
@stennie thank you. Yes, I discovered the after-start change too. I was wondering if it is possible to alter initial config document but reconfiguring it after start also works for me.

**Comment by apanagiotou** [comment]
Could you please elaborate on how you did it @igorsol ?

**Comment by igorsol** [comment]
@apanagiotou I did something like this:
1. start replica set  with mtools
2. run mongo shell
3. execute commands like this:
``` 
var cfg = rs.conf()
cfg.writeConcernMajorityJournalDefault=false
rs.reconfig(cfg 
```
