### ISSUE TITLE
mtools commands in capturing mongoDB queries

### ISSUE THREAD

**Issue by nandankamat50** [rueckstiess/mtools#632]
Hi Team,
I am new in mtool . I did a pip and instaleld in /tmp dir in mongodb server. 
I need to know how to start mtools and commands to capture slow queries from mongoDB logs etc.
Requesting for help .

 
### Environment

| Software         | Version
| ---------------- | -------
| mtools           | 
| MongoDB server   | 
| Operating system |

**Comment by stennie** [comment]
@nandankamat50 The [mtools documentation](http://blog.rueckstiess.com/mtools/) covers all of the tools and available command-line parameters.

You might find this answer on Server Fault a helpful starting point for reviewing your queries: [Understanding IXSCAN and COLLSCAN in MongoDB logs](https://serverfault.com/a/829407/129454).

You may also want to look into adjusting the [threshold for slow queries](https://docs.mongodb.com/manual/tutorial/manage-the-database-profiler/#specify-the-threshold-for-slow-operations), which is 100ms by default.

If you have further questions about working with MongoDB log files, I'd suggest starting a new discussion on the [mongodb-user group](https://groups.google.com/group/mongodb-user) with more information including your specific version of MongoDB (x.y.z), type of deployment (standalone, replica set, or sharded cluster), and what you've tried so far.

Regards,
Stennie
