### ISSUE TITLE
Improve audit log support for replica sets / shards in mlaunch

### ISSUE THREAD

**Issue by rseichter** [rueckstiess/mtools#633]
With mlaunch 1.4.1 it does not seem to be possible to configure individual audit log files and -filters for replica set members. The command line options `--auditPath` and `--auditFilter` are currently shared across all members, which limits usability.

It would be helpful if the audit file path could be specified relative to the dbpath. As for individual audit log filters, I unfortunately don't have an easy solution.

**Comment by stennie** [comment]
@rseichter `mlaunch` is only intended for standing up local test environments. For more advanced per-host options you could perhaps launch a deployment and then stop individual host(s) to restart with different options.

> As for individual audit log filters, I unfortunately don't have an easy solution.

Can you expand on the use case for having different audit filters per replica set member?

Thanks,
Stennie

**Comment by rseichter** [comment]
@stennie I am aware that `mlaunch` is meant for local testing environments only, and it does a good job of it. So far, auditing-related options seem to be treated as unknown by mlaunch and are thus passed along unmodified (and identically) to each `mongod`. Hence, I can easily spin up a replica set when I need it, as long as I don't need to configure auditing. In the latter case I am left with only my own shell scripts which I use to generate YAML config files for all nodes.

Regarding use cases: I sometimes want to audit all DML actions on a subset of nodes of a replica set, while I may only be interested on the actions of particular users on other nodes, and I'd not wish to audit a delayed secondary node at all. There are many possible combinations.

**Comment by stennie** [comment]
Passing per-host options is getting more complicated than the command-line test scenarios envisioned for `mlaunch`, so there are no current plans to add more parameters for this.

Aside from restarting individual members witth different options, you could also modify options in the  generated `.mlaunch_startup` file and then `mlaunch restart` to use the new options.

Regards,
Stennie
