### ISSUE TITLE
mlaunch failing to connect to a standalone SSL mongod

### ISSUE THREAD

**Issue by p-mongo** [rueckstiess/mtools#654]
I tried launching a cluster with this command:

<pre>
  mlaunch --single --dir $dir --name ruby-driver-rs \
    --wiredTigerCacheSizeGB 1 --setParameter enableTestCommands=1 --port 27400 \
    --sslMode requireSSL --sslPEMKeyFile `pwd`/cert/127.0.0.1.pem \
    --binarypath /usr/bin
</pre>

It has --sslMode and --sslPEMKeyFile set.

The cluster was launched, however mtools was sitting (hanging) for a long time with no output. Adding --verbose produced:

<pre>
waiting for nodes to start...                                                                                                       
</pre>

Examining mlaunch source, it looks for SSL args in:

<pre>
        for parser in self.ssl_args, self.ssl_client_args:
</pre>

The two arguments I passed in are in neither of these option groups, hence it seems that the mongo client was created without SSL being set and was trying to connect to my SSL mongod via a non-SSL connection, which then wouldn't work.

The following quick hack fixes this issue: https://github.com/rueckstiess/mtools/compare/develop...p-mongo:ssl-single-fix?expand=1

I'm sure there is a better way to accomplish this though.

### Expected behavior

mlaunch should be able to launch a standalone SSL mongod with a self-signed certificate successfully.

### Actual/current behavior

mlaunch does launch the mongod but hangs trying to connect to it.

### Steps to reproduce the actual/current behavior

<pre>
  mlaunch --single --dir $dir --name ruby-driver-rs \
    --wiredTigerCacheSizeGB 1 --setParameter enableTestCommands=1 --port 27400 \
    --sslMode requireSSL --sslPEMKeyFile `pwd`/cert/127.0.0.1.pem \
    --binarypath /usr/bin
</pre>

### Environment

| Software         | Version
| ---------------- | -------
| mtools           |  develop
| MongoDB server   | 3.6.5
| Operating system | Debian testing

**Comment by stennie** [comment]
Thanks @p! We didn't have a better suggestion so have merged the fix from your branch :)

Regards,
Stennie
