### ISSUE TITLE
mlaunch fails to configure a working replica set but still exits with successful status

### ISSUE THREAD

**Issue by p-mongo** [rueckstiess/mtools#659]
I think #654 triggers this, though I have a larger issue with this happening in non-SSL replica sets.

### Actual/current behavior

It appears that if mlaunch is unable to configure a replica set (initiate it and add all members), mlaunch still exits with a successful status. Later on operations against the replica set fail because it's not actually a working replica set (e.g., all nodes are in ghost state).
 
### Expected behavior

If a replica set was requested to be launched, and mlaunch didn't configure the cluster to be a working replica set, mlaunch should exit with an error code.

### Steps to reproduce the actual/current behavior

#654 is probably a good way to reproduce this issue reliably.

When configuring replica sets, mlaunch needs to wait for the cluster to configure itself (see https://stackoverflow.com/questions/31387053/cant-create-user/50397775#50397775).

### Environment

| Software         | Version
| ---------------- | -------
| mtools           | last release
| MongoDB server   | 4.0.0-rc6
| Operating system | Debian Testing

**Comment by kevinadi** [comment]
Thanks for the bug report @p-mongo 

Since #654 was fixed, could you give an example command line where it creates a non-working replica set? I'd like to understand if any part of the code is not reporting errors properly.

**Comment by p-mongo** [comment]
Consider https://github.com/rueckstiess/mtools/blob/develop/mtools/mlaunch/mlaunch.py#L1661. This function never propagates OperationFailure. If retries are exhausted it returns which is the same behavior as if it successfully executed replSetInitiate.

I imagine a way to reproduce this behavior is to start a cluster with auth and then drop auth parameters when connecting to it later to configure the replica set.

**Comment by p-mongo** [comment]
https://github.com/rueckstiess/mtools/blob/develop/mtools/mlaunch/mlaunch.py#L134 - the function does not signal failure to shut down mongod to its caller.

**Comment by stennie** [comment]
Fixed via #858
