### ISSUE TITLE
SSL parameters to mlaunch are not documented on website

### ISSUE THREAD

**Issue by p-mongo** [rueckstiess/mtools#666]
http://blog.rueckstiess.com/mtools/mlaunch.html does not appear to include the word "SSL", though https://github.com/rueckstiess/mtools/commit/7e2dfe3e8c189b7f32dabc44ca589751dfaaddaa suggests mlaunch does support SSL.

**Comment by stennie** [comment]
@p-mongo Support for SSL parameters was added in mtools 1.3.1 via PR #127.

`mlaunch init --help` includes the supported parameters, but this missed being added to the docs page.

Regards,
Stennie
