### ISSUE TITLE
Export logs to xlsx file

### ISSUE THREAD

**Issue by twblamer** [rueckstiess/mtools#671]
I would like to add a new script called `mlogexcel` that exports the log to an .xlsx file (using openpyxl). It is just a simple conversion of log lines to spreadsheet rows, but this is still useful for visually inspecting large logs and allowing the use of Excel features as one sees fit (sorting, coloring, column rearrangement, etc).

I have code + tests + a doc page written; I plan to post a PR sometime soon.

**Comment by stennie** [comment]
@twblamer Thanks for the pull request!

The changes to LogEvent are fine, but we're not sure on trying to support Excel integration directly.

There might be a more universal approach for supporting Excel. For example, adding a `--csv` export option for `mlogfilter ` . The existing `--json` option can also be used to import logs into MongoDB for analysis without being subject to [Excel limitations](https://support.office.com/en-us/article/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3).

I suggest maintaining `mlogexcel` in your own repo for now; we can also make mention of this related tool in the mtools documentation.

If you're OK with that approach, I'll cherrypick the changes from this PR outside of `mlogexcel` and add a docs mention of the upstream repo when ready (`twblamer/mlogexcel`?).

How does that sound?

Regards,
Stennie

**Comment by twblamer** [comment]
Thanks for the feedback. I agree that csv output would have more general utility, and I could probably feed that into a standalone script to get the Excel output I want. I'll take a second look at `mlogfilter --json` as well.

Please go ahead and cherry-pick the changes as you deem appropriate.

**Comment by stennie** [comment]
@twblamer The LogEvent changes have been merged to `develop` via d41c3c9.

Thanks,
Stennie
