### ISSUE TITLE
Add support for Python 3.7

### ISSUE THREAD

**Issue by stennie** [rueckstiess/mtools#682]
Review [release highlights](https://docs.python.org/3/whatsnew/3.7.html) for Python 3.7:
- [ ] Add `py37` env to tox
- [ ] Update requirements to modern package versions
- [ ] Ensure all tests are passing  on 3.6 and 3.7
- [ ] Add to Travis
- [ ] Update supported versions in README

Related issues: #681

**Comment by stennie** [comment]
Fixed via PR#714

**Comment by NuckChorris** [comment]
Hey, wondering if you could cut a release of 1.6.0?  It's been a few months and I'm guessing you probably just forgot to push to pip 🙂 thanks!

**Comment by stennie** [comment]
@NuckChorris Haven't forgotten -- had a few more changes queued up for the [1.6.0 release](https://github.com/rueckstiess/mtools/milestone/30) and needed to find the tuits for review. 

Expecting that will be wrapped up this month, but if you can't wait you could [install from source](http://blog.rueckstiess.com/mtools/install.html#installation-from-source) if you want to run the current `develop` branch.

Cheers,
Stennie
