### ISSUE TITLE
How to install mtools in windows 10

### ISSUE THREAD

**Issue by yogeshtj889** [rueckstiess/mtools#693]
I am first time installing mtools on window using python.

I am using cmd for installing mtools "**pip install mtools[all]**".

It is giving error so I installed mtools in some parts as below,
1.**pip install mtools[mlogfilter]**
2.**pip install mtools[mloginfo]**

these two got installed but while installing mplotqueries as per brelow
3.**pip install mtools[mplotqueries]**
given error as below,

**D:\mongodb>**pip install mtools[mplotqueries]**
Requirement already satisfied: mtools[mplotqueries] in c:\program files\python37\lib\site-packages (1.5.3)
Requirement already satisfied: six in c:\program files\python37\lib\site-packages (from mtools[mplotqueries]) (1.12.0)
Requirement already satisfied: python-dateutil==2.7 in c:\program files\python37\lib\site-packages (from mtools[mplotqueries]) (2.7.0)
Collecting matplotlib==1.4.3 (from mtools[mplotqueries])
Using cached https://files.pythonhosted.org/packages/bb/ac/485df0ecb15aa6fec1991945dc0cabfeb724a64f6729e34bab3c6a766813/matplotlib-1.4.3.tar.gz
ERROR: Complete output from command python setup.py egg_info:
ERROR: ============================================================================
Edit setup.cfg to change the build options

BUILDING MATPLOTLIB
            matplotlib: yes [1.4.3]
                python: yes [3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019,
                        22:22:05) [MSC v.1916 64 bit (AMD64)]]
              platform: yes [win32]

REQUIRED DEPENDENCIES AND EXTENSIONS
                 numpy: yes [version 1.14.5]
                   six: yes [using six version 1.12.0]
              dateutil: yes [using dateutil version 2.7.0]
                  pytz: yes [using pytz version 2019.1]
               tornado: yes [using tornado version 3.2.1]
             pyparsing: yes [using pyparsing version 2.4.0]
                 pycxx: yes [Official versions of PyCXX are not compatible
                        with matplotlib on Python 3.x, since they lack
                        support for the buffer object.  Using local copy]
                libagg: yes [pkg-config information for 'libagg' could not
                        be found. Using local copy.]
              freetype: no  [The C/C++ header for freetype (ft2build.h)
                        could not be found.  You may need to install the
                        development package.]
                   png: no  [The C/C++ header for png (png.h) could not be
                        found.  You may need to install the development
                        package.]
                 qhull: yes [pkg-config information for 'qhull' could not be
                        found. Using local copy.]

OPTIONAL SUBPACKAGES
           sample_data: yes [installing]
              toolkits: yes [installing]
                 tests: yes [nose 0.11.1 or later is required to run the
                        matplotlib test suite.  pip/easy_install may attempt
                        to install it after matplotlib. / using
                        unittest.mock]
        toolkits_tests: yes [nose 0.11.1 or later is required to run the
                        matplotlib test suite.  pip/easy_install may attempt
                        to install it after matplotlib. / using
                        unittest.mock]

OPTIONAL BACKEND EXTENSIONS
                macosx: no  [Mac OS-X only]
                qt5agg: no  [PyQt5 not found]
                qt4agg: no  [PyQt4 not found]
                pyside: no  [PySide not found]
               gtk3agg: no  [Requires pygobject to be installed.]
             gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                gtkagg: no  [Requires pygtk]
                 tkagg: no  [The C/C++ header for Tk (tk.h) could not be
                        found.  You may need to install the development
                        package.]
                 wxagg: no  [requires wxPython]
                   gtk: no  [Requires pygtk]
                   agg: yes [installing]
                 cairo: no  [cairocffi or pycairo not found]
             windowing: yes [installing, installing]

OPTIONAL LATEX DEPENDENCIES
                dvipng: no
           ghostscript: no
                 latex: no
               pdftops: no

============================================================================
                        * The following required packages can not be built:
                        * freetype, png
----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-kfokd2ty\matplotlib\

D:\mongodb>**

Can any one give solution...

**Comment by stennie** [comment]
@yogeshtj889 Since you are installing with Python 3.x, it requires using `pip3` instead of `pip` (which will install Python 2.x dependencies). This should be made clearer in the installation instructions, which were originally written when only Python 2.7 was supported.

I would also note that mtools doesn't support Python 3.7 yet due to some backward-incompatible changes in exception handling. This will be fixed by way of #682, but until then I would recommend using Python 3.6.

Please confirm if you are able to successfully install using Python 3.6 and `pip install mtools[all]`.

Regards,
Stennie

**Comment by yogeshtj889** [comment]
now using **python 3.6.7**

I have installed everything in mtools except **mplotqueries**

using 
pip install mtools[mlaunch]
pip install mtools[mlogvis]
pip install mtools[mloginfo]
pip install mtools[mlogfilter]

now for **mplotqueries** I am getting below error

D:\mongodb>pip install mtools[mplotqueries]
Requirement already satisfied: mtools[mplotqueries] in c:\program files\python36\lib\site-packages (1.5.3)
Requirement already satisfied: six in c:\program files\python36\lib\site-packages (from mtools[mplotqueries]) (1.12.0)
Requirement already satisfied: python-dateutil==2.7 in c:\program files\python36\lib\site-packages (from mtools[mplotqueries]) (2.7.0)
Collecting matplotlib==1.4.3 (from mtools[mplotqueries])
  Using cached https://files.pythonhosted.org/packages/bb/ac/485df0ecb15aa6fec1991945dc0cabfeb724a64f6729e34bab3c6a766813/matplotlib-1.4.3.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: ============================================================================
    Edit setup.cfg to change the build options

    BUILDING MATPLOTLIB
                matplotlib: yes [1.4.3]
                    python: yes [3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018,
                            13:35:33) [MSC v.1900 64 bit (AMD64)]]
                  platform: yes [win32]

    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.14.5]
                       six: yes [using six version 1.12.0]
                  dateutil: yes [using dateutil version 2.7.0]
                      pytz: yes [pytz was not found. pip will attempt to install
                            it after matplotlib.]
                   tornado: yes [tornado was not found. It is required for the
                            WebAgg backend. pip/easy_install may attempt to
                            install it after matplotlib.]
                 pyparsing: yes [pyparsing was not found. It is required for
                            mathtext support. pip/easy_install may attempt to
                            install it after matplotlib.]
                     pycxx: yes [Official versions of PyCXX are not compatible
                            with matplotlib on Python 3.x, since they lack
                            support for the buffer object.  Using local copy]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [The C/C++ header for png (png.h) could not be
                            found.  You may need to install the development
                            package.]
                     qhull: yes [pkg-config information for 'qhull' could not be
                            found. Using local copy.]

    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: yes [nose 0.11.1 or later is required to run the
                            matplotlib test suite.  pip/easy_install may attempt
                            to install it after matplotlib. / using
                            unittest.mock]
            toolkits_tests: yes [nose 0.11.1 or later is required to run the
                            matplotlib test suite.  pip/easy_install may attempt
                            to install it after matplotlib. / using
                            unittest.mock]

    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PyQt5 not found]
                    qt4agg: no  [PyQt4 not found]
                    pyside: no  [PySide not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: no  [The C/C++ header for Tk (tk.h) could not be
                            found.  You may need to install the development
                            package.]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: yes [installing, installing]

    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: no
                     latex: no
                   pdftops: no

    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\YOGESH~1.JAD\AppData\Local\Temp\pip-install-soh5cian\matplotlib\


Kindly help.

**Comment by PeterMolDigi** [comment]
Hello yogeshtj889...
Did you manage to install the complete mtools set because I have the same problem as you discribed above...

**Comment by yogeshtj889** [comment]
Except mplotqueries everything is installed after some time I give up on it...

**Comment by PeterMolDigi** [comment]
After installing the complete Build Tools for Visual Studio 2019 set, the mlaunch install succeeded.
But I still have the same problems with the install of mplotqueries] : 
pip install mtools[mplotqueries]

I allready installed manually the matplotlib library : 
python -m pip install matplotlib
But no success ! Any help somebody ?

**Comment by howardkhl** [comment]
I successfully installed `mtools` and started using `mplotqueries`.

Install `Python 3.6.8` (32bit)
https://www.python.org/ftp/python/3.6.8/python-3.6.8.exe
Upgrade `pip` to latest
	`python -m pip install --upgrade pip`
Install `mtools` thru cmd (Run as administrator)
	`pip install -U matplotlib`
	`pip install -U numpy`
	`pip install mtools[all]`

**Comment by howardkhl** [comment]
@yogeshtj889 the version of `matplotlib` i've installed seems much newer (3.1.1) than your cached version (1.4.3), try update your pip and install updated matplotlib
python -m pip install --upgrade pip
pip install -U matplotlib
pip install -U numpy
pip install mtools[all]

C:\windows\system32>pip install -U matplotlib
Collecting matplotlib
  Downloading https://files.pythonhosted.org/packages/39/ae/60ec3ec8f8a18c5eef71c6dff7ed0dfa0cd2f2d57b6691e595e2bc43325f/matplotlib-3.1.1-cp36-cp36m-win32.whl (8.9MB)
     |████████████████████████████████| 8.9MB 3.2MB/s

**Comment by yogeshtj889** [comment]
but by default it is taking 1.4.3 for matplotlib while executing **pip3 install mtools[all]**. what we can do about it.  

```
C:\Windows\system32>pip3 install mtools[all]
Requirement already satisfied: mtools[all] in c:\program files (x86)\python36-32\lib\site-packages (1.5.3)
Requirement already satisfied: six in c:\program files (x86)\python36-32\lib\site-packages (from mtools[all]) (1.12.0)
Requirement already satisfied: python-dateutil==2.7 in c:\program files (x86)\python36-32\lib\site-packages (from mtools[all]) (2.7.0)
Collecting matplotlib==1.4.3 (from mtools[all])
  Using cached https://files.pythonhosted.org/packages/bb/ac/485df0ecb15aa6fec1991945dc0cabfeb724a64f6729e34bab3c6a766813/matplotlib-1.4.3.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\python36-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\YOGESH~1.JAD\\AppData\\Local\\Temp\\pip-install-3b29m5zw\\matplotlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\YOGESH~1.JAD\\AppData\\Local\\Temp\\pip-install-3b29m5zw\\matplotlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\YOGESH~1.JAD\AppData\Local\Temp\pip-install-3b29m5zw\matplotlib\
    Complete output (71 lines):
```

**Comment by PeterMolDigi** [comment]
Same problem…


Van: Howard Lee [mailto:notifications@github.com]
Verzonden: woensdag 4 september 2019 20:54
Aan: rueckstiess/mtools
CC: Peter Mol; Comment
Onderwerp: Re: [rueckstiess/mtools] How to install mtools in windows 10 (#693)


@yogeshtj889<https://github.com/yogeshtj889> the version of matplotlib i've installed seems much newer (3.1.1) than your cached version (1.4.3), try update your pip and install updated matplotlib
python -m pip install --upgrade pip
pip install -U matplotlib
pip install -U numpy
pip install mtools[all]

C:\windows\system32>pip install -U matplotlib
Collecting matplotlib
Downloading https://files.pythonhosted.org/packages/39/ae/60ec3ec8f8a18c5eef71c6dff7ed0dfa0cd2f2d57b6691e595e2bc43325f/matplotlib-3.1.1-cp36-cp36m-win32.whl (8.9MB)
|████████████████████████████████| 8.9MB 3.2MB/s

**Comment by howardkhl** [comment]
[matplotlib v1.4.3](https://github.com/matplotlib/matplotlib/releases/tag/v1.4.3) was released in 2015, very outdated. Not sure why your pip kept referring to it. What version pip are you using, have you tried upgrade it first?
`python -m pip install --upgrade pip`

Maybe try [sandboxie ](https://www.sandboxie.com/) to start a new environment from scratch and see if it works better?

**Comment by stennie** [comment]
mtools 1.6.0 has been released and updates old package requirements (including `matplotlib`) to recent versions which should be less problematic to install.

If anyone is still having issues installing mtools, please create a new GitHub issue report with details for your environment: O/S version, Python version, mtools version, and any error messages encountered during install.

Thanks,
Stennie
