### ISSUE TITLE
Remove support for Python 2.7

### ISSUE THREAD

**Issue by stennie** [rueckstiess/mtools#694]
All good things must come to an end, including Python 2 which will reach [End Of Life](https://www.python.org/dev/peps/pep-0373/#update) in January, 2020.

It's time to remove support for Python 2.x and focus on Python 3.6+.

mtools 1.5.x will be the last release series to support Python 2.7.

**Comment by jamesbroadhead** [comment]
Would you consider extending this until the 2020 deadline? 
We have a fair bit of internal tooling which is py2, and is in the process of being deprecated.
