### ISSUE TITLE
mplotqueries --replicaset 

### ISSUE THREAD

**Issue by njcosta** [rueckstiess/mtools#703]
Plot replication events: colored states, elections, restarts

**Comment by stennie** [comment]
@njcosta This sounds similar to [`mplotqueries --type rsstate`](http://blog.rueckstiess.com/mtools/mplotqueries.html#replica-set-state-plot).

Can you clarify what changes you are envisioning?

Thanks,
Stennie

**Comment by njcosta** [comment]
it's the same. closing this issue.
