### ISSUE TITLE
Require minimum dependency versions rather than exact

### ISSUE THREAD

**Issue by LouisPlisso** [rueckstiess/mtools#738]
### Expected behavior
`pip install mtools[all]` should work

### Actual/current behavior
with matplotlib 3.1.1 installed, `pip install mtools[all]` fails with

`Installing collected packages: matplotlib, pymongo, psutil
  Found existing installation: matplotlib 3.1.2
    Uninstalling matplotlib-3.1.2:
      Successfully uninstalled matplotlib-3.1.2
    Running setup.py install for matplotlib ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/louis.plissonneau/git_repos_bar_go/nhtt/env/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/96/xtb1z4sx37g4l8nxl7vz48qc0000gp/T/pip-install-c89q_ocr/matplotlib/setup.py'"'"'; __file__='"'"'/private/var/folders/96/xtb1z4sx37g4l8nxl7vz48qc0000gp/T/pip-install-c89q_ocr/matplotlib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/96/xtb1z4sx37g4l8nxl7vz48qc0000gp/T/pip-record-1c5y2c5x/install-record.txt --single-version-externally-managed --compile --install-headers /Users/louis.plissonneau/git_repos_bar_go/nhtt/env/include/site/python3.7/matplotlib
         cwd: /private/var/folders/96/xtb1z4sx37g4l8nxl7vz48qc0000gp/T/pip-install-c89q_ocr/matplotlib/
    Complete output (2238 lines):
    ============================================================================`

### Steps to reproduce the actual/current behavior
`pip install matplotlib
pip install mtools[all]`

### Environment

| Software         | Version
| ---------------- | -------
| mtools           | 
| MongoDB server   | 
| Operating system | Catalina 10.15.1

**Comment by stennie** [comment]
@LouisPlisso We had exact versions specified as unpinning caused some issues previously when we were much farther behind. Will loosen the requirements to minimum versions.

Cheers,
Stennie

**Comment by LouisPlisso** [comment]
Thanks @stennie
