### ISSUE TITLE
mloginfo --queries misses pattern for remove command

### ISSUE THREAD

**Issue by niccottrell** [rueckstiess/mtools#742]
### Expected behavior
When run on the following log line, I would like to see the pattern `{ blah.abc.uID: 1 }` included:

`2019-11-13T11:33:39.626+0000 I WRITE    [conn23773] remove MyDb.MyColl command: { q: { blah.abc.uID: "H062634" }, limit: 0 } planSummary: COLLSCAN keysExamined:0 docsExamined:139649 ndeleted:1 keysDeleted:3 numYields:1091 locks:{ Global: { acquireCount: { r: 1093, w: 1093 } }, Database: { acquireCount: { w: 1093 } }, Collection: { acquireCount: { w: 1092 } }, oplog: { acquireCount: { w: 1 } } } 308ms`

### Actual/current behavior
Currently the DB, collection and operation is detected correctly, but not the pattern:
```
QUERIES
                                                                                          
namespace                     operation    pattern    count    min (ms)    max (ms)    mean (ms)    95%-ile (ms)    sum (ms)

MyDb.MyColl    remove       None           2         281         308        294.5          306.65    589
```

### Environment

| Software         | Version
| ---------------- | -------
| mtools           |  1.5.3 
| MongoDB server   | 4.0

**Comment by stennie** [comment]
Interesting logging quirk .. `remove` commands in 3.6+ appear to log `q:` instead of `query:`, but older logs definitely used `query:`.
