### ISSUE TITLE
Deprecate mlogvis

### ISSUE THREAD

**Issue by stennie** [rueckstiess/mtools#776]
`mlogvis` has limited utility with modern versions of MongoDB and several interactive options are no longer working.

This script hasn't been actively updated since 2013 and should be deprecated.

**Comment by nstremsd** [comment]
Don't work for me since protocol-less with //d3js.org/d3.v3.min.js but work with /d3js.org/d3.v3.min.js

**Comment by stennie** [comment]
@nstremsd `mlogvis` doesn't provide a lot of insight and hasn't been actively maintained since 2013. It will be removed in an upcoming version of mtools so I suggest using `mplotqueries` instead.

Regards,
Stennie
