### ISSUE TITLE
mloginfo "SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Simone-cogno** [rueckstiess/mtools#777]
I try to use mloginfo but it fails to lunch because of a sytax error.

Reference ticket that was previously closed without a valid solution:
https://github.com/rueckstiess/mtools/issues/771#event-2940311781
 
### Expected behavior

mloginfo should work, and not having syntax errors.

### Actual/current behavior

` mloginfo /usr/local/var/mongodb/info.log --queries
Traceback (most recent call last):
  File "/usr/local/bin/mloginfo", line 9, in <module>
    load_entry_point('mtools==1.6.1', 'console_scripts', 'mloginfo')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/mtools/mloginfo/mloginfo.py", line 75
    timezone = f"UTC {tzdt.strftime('%z')}"
                                          ^
SyntaxError: invalid syntax`

### Environment

I have installed in the machine python2 and  python3.

| Software         | Version
| ---------------- | -------
| mtools           | 1.6.1
| MongoDB server   | 4.2
| Operating system | Mac OS X

**Comment by stennie** [comment]
@Simone-cogno The solution is as per my last comment in your previous issue: mtools 1.6+ no longer supports Python 2.7 so you need to either:
 - upgrade to Python 3.6 or newer to install mtools
 - install the last version to support Python 2.7 (`pip install mtools==1.5.3`).

Note: [Python 2 reached end of life on Jan, 2020](https://www.python.org/doc/sunset-python-2/).

Regards,
Stennie

**Comment by Simone-cogno** [comment]
@stennie can you read my post please? I have python3.6 installed!

**Comment by stennie** [comment]
> **I have python3.6 already installed on the machine**!

Closing the loop since there were a few duplicates of this question. The solution is as per [my comment on #778](https://github.com/rueckstiess/mtools/issues/778#issuecomment-579009839).

The error message indicates a Python 2.7 path so you likely have both Python 2 & Python 3 installed (with Python 2 as the default):
> "/System/Library/Frameworks/Python.framework/Versions/2.7/"

You need to make sure you are installing mtools 1.6+ into a Python 3 environment. If you have both Python 2 & 3 interpreters in your path, `pip3` and `python3` are more explicit aliases for Python 3.

Regards,
Stennie
