### ISSUE TITLE
check OS/Python version before allowing the install newest mtools if not compatible 

### ISSUE THREAD

**Issue by yulin210** [rueckstiess/mtools#788]
In my env of Ubuntu 14.04.6 LTS" along with latest Python 3.4, latest mtools (1..6.2) was installed successfully. However 'mlaunch' failed to use to create a replSet.

### Expected behavior
   A ReplSet of 3-node servers should be created with no error.

### Actual/current behavior
   **mlaunch failed as following**

```
   mlaunch --replicaset --name "m312rs" --port 30000 --wiredTigerCacheSizeGB 0.5 --oplogSize 100
Traceback (most recent call last):
  File "/usr/local/bin/mlaunch", line 9, in <module>
    load_entry_point('mtools==1.6.2', 'console_scripts', 'mlaunch')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/mtools/mlaunch/mlaunch.py", line 1535
    **result.append(f'"{arg}"')**
                           ^
**SyntaxError: invalid syntax**
```

### Additional context
  result.append(f'"{arg}"') is not supported syntax in Python 3.4.

**Comment by stennie** [comment]
@yulin210 The documentation is clear that Python 3.6 is required, but will look into adding a check during install as well. Thanks for the suggestion!

Regards,
Stennie

**Comment by yulin210** [comment]
Totally agree! The check for Python as a requirement will be much helpful. Thanks @stennie for the quick fix.
