### ISSUE TITLE
mplotqueries --overlay example not working

### ISSUE THREAD

**Issue by vgrippa** [rueckstiess/mtools#818]
The example provided on the page is not working:

```
grep "oplog.rs" mongod.log | mplotqueries --type durline --overlay
mplotqueries mongod.log --group operation
```

```
vgrippa-mac:temp vgrippa$ grep "oplog.rs" mongod.log | mplotqueries --type durline --overlay
Error: cannot serialize '_io.TextIOWrapper' object
vgrippa-mac:temp vgrippa$ mplotqueries mongod.log --group operation
parsing mongod.log [========================                ] 58.8 %
```

### Expected behavior
Provide overlay functionality.

### Actual/current behavior
An error is thrown and overlay does not happen.

### Environment

vgrippa-mac:temp vgrippa$ mplotqueries --version
mtools version 1.6.4 || Python 3.7.3 (default, Mar 6 2020, 22:34:30) [Clang
11.0.3 (clang-1103.0.32.29)]

MongoDB v3.6.8

MacOS Catalina 10.15.6

**Comment by stennie** [comment]
Hi @vgrippa,

Thanks for the bug report and apologies for the delay in investigation. As it turns out, the `--overlay` feature was not working in Python 3 with piped input.

I've committed a fix for the next release of mtools (1.7.0).

Regards,
Stennie
