### ISSUE TITLE
zsh: no matches found: mtools[all]

### ISSUE THREAD

**Issue by nasht00** [rueckstiess/mtools#828]
on macOS, following the documentation to install:

`pip3 install mtools[all]`

I get 

`zsh: no matches found: mtools[all]`

**Comment by p-mongo** [comment]
You need to quote the brackets in zsh.

````
pip3 install 'mtools[all]'
```

**Comment by p-mongo** [comment]
The documentation at http://blog.rueckstiess.com/mtools/install.html should be updated to use the quotes also.
