### ISSUE TITLE
MongoDB 4.4:: mloginfo:: Error: <mongod.log> does not appear to be a supported MongoDB log file format

### ISSUE THREAD

**Issue by hanksu-deloitte** [rueckstiess/mtools#837]
### Environment

| Software         | Version
| ---------------- | -------
| mtools           |
| mloginfo       |
| MongoDB server   | 4.4.0
| Operating system | RHEL 7.8

**Comment by stennie** [comment]
@hanksu-deloitte That is expected at the moment and waiting on #806.

For alternative tools, please see https://github.com/rueckstiess/mtools/issues/806#issuecomment-688087988.

Regards,
Stennie
