### ISSUE TITLE
mplotqueries --storagestats displaying duration instead of the number of bytes read 

### ISSUE THREAD

**Issue by linnashan06** [rueckstiess/mtools#860]
### Expected behavior

The read storage statistics can be plotted on the graph with the use of --storagestats flag. The number of bytes read at particular time is mapped onto the graph.
### Actual/current behavior

The lable of the axis Y is duraing ms
### Steps to reproduce the actual/current behavior

mplotqueries mongodb.log --storagestats

### Environment

| Software         | Version
| ---------------- | -------
| mtools           | 1.7.0
| Python           | 3.8.5
| MongoDB server   | 4.2.19
| Operating system | Atlas

**Comment by stennie** [comment]
Hi @linnashan06,

Unfortunately it looks like this option was planned to be implemented via #711 but is only a stub. I will remove the current stub and create a ticket for the implementation.

Regards,
Stennie
