### ISSUE TITLE
Please list what versions of MongoDB are support by this tool

### ISSUE THREAD

**Issue by SteveH-US** [rueckstiess/mtools#863]
Please list what versions of MongoDB are support by this tool. 

There have been some changes to the log format in v4.2 and in big changes for v4.4 (with structured logging). It is not clear from the [changes to mtools](http://rueckstiess.github.io/mtools/changelog.html) what version of MongoDB logs are supported.

**Comment by skijash** [comment]
Hey guys,
I was looking into support for 4.4 log format, and if you would be organising a sprint on Mongo World, I'd be interested in joining. Let me know.
