### ISSUE TITLE
Replica set initialization announcement is printed after initialization is complete 

### ISSUE THREAD

**Issue by p-mongo** [rueckstiess/mtools#868]
Code: https://github.com/rueckstiess/mtools/blob/develop/mtools/mlaunch/mlaunch.py#L1844

The printing of "initializing replica set" happens after the command is sent to the server to do so. If the command failed the announcement is printed after all of the retries finished.

The announcement should precede the command.

**Comment by stennie** [comment]
Belated thanks @p-mongo !

Cheers,
Stennie

**Comment by stennie** [comment]
Fixed via ba01571
