### ISSUE TITLE
mlaunch - would it be possible to config a multihost cluster with mlaunch

### ISSUE THREAD

**Issue by dunckerr** [rueckstiess/mtools#910]
feature request, or is this possible at the moment?

### Expected behavior
Example topology would be
3 hosts, each running a mongos and 1 leg of a 3 member replica set, ie
host0
mongos0
0.rs0, 0.rs1, and 0.rs2, 0.config mongod

host1
mongos1
1.rs0, 1.rs1, and 1.rs2, 1.config mongod

host2
mongos2
2.rs0, 2.rs1, and 2.rs2, 2.config mongod

### Actual/current behavior
not available

### Additional context
useful because this is how we run our production mongo setup

**Comment by stennie** [comment]
Hi @dunckerr,

`mlaunch` intentionally only supports local development deployments.

For a multihost production cluster I would look into tooling that is designed for orchestration, resource management, and resilience.

For example, the MongoDB Kubernetes operators:
 - [MongoDB Community Operator](https://github.com/mongodb/mongodb-kubernetes-operator) for replica sets
 - [MongoDB Enterprise Operator](https://www.mongodb.com/docs/kubernetes-operator/stable/) for replica sets and sharded clusters

Regards,
Stennie
