### ISSUE TITLE
mloginfo different output formats

### ISSUE THREAD

**Issue by rueckstiess** [rueckstiess/mtools#97]
See André's logsum:
https://github.com/andredefrere/logtools/blob/master/logsum/outifier.py

Output in JSON and JIRA markup would be the most helpful initially.

**Comment by stennie** [comment]
`mloginfo` has evolved with more info sections which would have to be updated to support different formats. Output can be included in JIRA via inline quoting, but I suspect the original use case no longer exists :).

Closing this as a #wontfix to clean up the backlog.
